/* ════════════════════════════════════════════════════════════
   問 AI・智慧港口(Engage with AI)
   E2:說明 AI 如何完成任務(破解常見迷思)
       Basic:知道 AI 是「根據資料規律產生輸出」的非人類工具,
             並不真的「懂」或「思考」。
   E3:判斷 AI 的輸出應該接受、修正還是退回
       Basic:知道為什麼 AI 的輸出需要查核,以及自己可以怎麼查核。
   ════════════════════════════════════════════════════════════ */

const ENGAGE_MODULE = {
  id: "engage", domain: "engage", tag: "問AI", scene: "智慧港口", bg: "BK1.png",
  npc: { name: "港務員阿浪", img: "NPC1half.png", standee: "NPC1.png" },
  compMeta: {
    E2: { label: "問 AI 2", name: "說明 AI 如何完成任務(破解迷思)" },
    E3: { label: "問 AI 3", name: "判斷 AI 輸出:接受・修正・退回" },
  },
  versions: {

    /* ───────────────────────── 版本 A ───────────────────────── */
    A: {
      desc: "說法分類雷達 + 包裹檢查員(接受/修正/退回)",
      steps: [
        { t: "dialog", who: "npc", lines: [
          "歡迎來到智慧港口!我是港務員阿浪,今天你是我的小小實習生!",
          "你看,那台自動吊車正把貨櫃吊到正確的位置。剛剛有人說:「哇,AI 吊車好聰明,它『知道』每個貨櫃要去哪!」",
          "嗯……它真的「知道」嗎?其實 AI 不是小人,也不會像你一樣思考。",
          "AI 是一種工具:它看過非常非常多的資料,從裡面找到「規律」,再用規律算出答案。它並不真的「懂」自己在做什麼。",
          "很多人會用錯誤的方式描述 AI。走,我們來當「說法偵探」,把怪怪的說法找出來!",
        ]},
        { t: "task", comp: "E2", kind: "learn", title: "說法偵探雷達", acts: [
          { type: "sort2",
            q: "港口裡流傳著這些說法,哪些是「怪怪的說法」,哪些「說得比較對」?",
            buckets: [
              { id: "myth", label: "怪怪的說法", icon: "🙅" },
              { id: "fact", label: "說得比較對", icon: "✅" },
            ],
            items: [
              { label: "掃描機「看得懂」字,就像人在閱讀", icon: "📦", bucket: "myth",
                fb: "掃描機不是真的「看懂」,它是把圖案跟學過的資料規律做比對。" },
              { label: "吊車 AI 從很多次搬運資料裡學到規律,才算出貨櫃放哪", icon: "🏗️", bucket: "fact",
                fb: "沒錯!AI 靠的是大量資料裡的規律,不是自己「想」出來的。" },
              { label: "導航 AI「希望」船平安,所以帶它走安全的路", icon: "🚢", bucket: "myth",
                fb: "AI 沒有「希望」或感覺,它只是依照資料算出一條建議路線。" },
              { label: "語音廣播 AI 是照著它學過的發音規律,把字變成聲音", icon: "📢", bucket: "fact",
                fb: "對!它是用學過的規律把文字轉成聲音,不是真的會「說話聊天」。" },
              { label: "AI 答錯的時候,是因為它今天心情不好", icon: "🌧️", bucket: "myth",
                fb: "AI 沒有心情!答錯通常是因為它學過的資料裡沒有類似的例子。" },
            ],
          },
          { type: "mcq",
            art: "🏗️📦📦📦",
            q: "所以,自動吊車到底是「怎麼」決定貨櫃放哪裡的?",
            opts: [
              { label: "它從過去大量搬運資料中學到規律,用規律算出位置", ok: true,
                fb: "答對了!這就是 AI 完成任務的方式:資料 → 規律 → 輸出。" },
              { label: "它自己想一想,就像人一樣懂了", fb: "AI 不會「想」,它沒有真的理解喔。" },
              { label: "吊車裡住著一個會開吊車的小精靈", fb: "哈哈,沒有小精靈!靠的是資料和規律。" },
            ],
          },
        ]},
        { t: "task", comp: "E2", kind: "quiz", title: "實習生檢定:AI 是怎麼做到的?", acts: [
          { type: "mcq", q: "下面哪一句話,最正確地描述 AI?",
            opts: [
              { label: "AI 是根據資料規律產生答案的工具", ok: true, fb: "正確!" },
              { label: "AI 是一種會思考的電子小人", fb: "AI 不是小人,也不會思考。" },
              { label: "AI 什麼都懂,像百科全書一樣不會錯", fb: "AI 沒有真的「懂」,也常常會錯。" },
            ]},
          { type: "mcq", q: "掃描機把包裹分類分得又快又準,是因為?",
            opts: [
              { label: "它看過大量包裹資料,學會了分類的規律", ok: true, fb: "沒錯!" },
              { label: "它讀懂了每個包裹的心事", fb: "包裹沒有心事,AI 也不會讀心。" },
              { label: "工人偷偷躲在裡面幫忙", fb: "不是喔,是資料規律的功勞。" },
            ]},
          { type: "mcq", q: "有同學說:「AI 廣播今天唸錯船名,它一定很難過。」這句話哪裡怪怪的?",
            opts: [
              { label: "AI 沒有感覺,不會難過;唸錯是因為資料或規律的問題", ok: true, fb: "答對了!" },
              { label: "沒有怪怪的,AI 當然會難過", fb: "AI 沒有情緒喔。" },
              { label: "怪的是 AI 不可能唸錯", fb: "AI 是會出錯的!" },
            ]},
          { type: "mcq", q: "AI 導航建議船走 B 航道。它「為什麼」給這個建議?",
            opts: [
              { label: "它比對過去的天氣與航行資料,算出 B 航道比較順", ok: true, fb: "正確!" },
              { label: "它昨天夢到 B 航道", fb: "AI 不會做夢啦!" },
              { label: "它想去 B 航道玩", fb: "AI 沒有想去哪裡玩的願望。" },
            ]},
          { type: "mcq", q: "如果 AI 沒看過「三角形的特殊貨櫃」的資料,它遇到時最可能?",
            opts: [
              { label: "容易出錯,因為它學過的規律裡沒有這種例子", ok: true, fb: "沒錯,資料裡沒有的,AI 就容易出錯。" },
              { label: "動動腦想一下就會了", fb: "AI 不會自己「動腦想」新東西。" },
              { label: "打電話問別的吊車", fb: "它不會這樣做喔。" },
            ]},
        ]},
        { t: "dialog", who: "npc", lines: [
          "太棒了,你已經知道 AI 的祕密:它靠「資料的規律」做事,不是真的會思考!",
          "叮叮叮——警報!掃描機把一箱「玩具」標成了「水果」!",
          "你看,AI 真的會出錯吧!所以 AI 給的答案,不能照單全收。",
          "從現在起,你是包裹檢查員!記住三步驟:看一看(AI 說什麼)、想一想(證據對不對)、再決定——",
          "可以「接受 ✅」、可以「修正 ✏️」,也可以「退回 🚫 再檢查一次」。上工囉!",
        ]},
        { t: "task", comp: "E3", kind: "learn", title: "包裹檢查員:接受・修正・退回", acts: [
          { type: "mcq", art: "📦🍎",
            scenario: "AI 標籤:「水果箱」。X 光影像:看到一顆顆圓圓的蘋果。",
            q: "你的決定是?",
            opts: [
              { label: "接受:證據跟 AI 說的一樣", icon: "✅", ok: true,
                fb: "很好!AI 的標籤和證據相符,可以放心接受。" },
              { label: "修正:改成別的標籤", icon: "✏️", fb: "先看看證據:X 光裡是蘋果,跟 AI 說的一樣喔。" },
              { label: "退回:再檢查一次", icon: "🚫", fb: "證據已經很清楚了,這箱可以直接判斷。" },
            ]},
          { type: "mcq", art: "📦🧸",
            scenario: "AI 標籤:「水果箱」。X 光影像:看到一隻毛茸茸的玩具熊。",
            q: "你的決定是?",
            opts: [
              { label: "接受:AI 說是水果就是水果", icon: "✅", fb: "等等!證據跟 AI 說的不一樣,不能照單全收。" },
              { label: "修正:把標籤改成「玩具箱」", icon: "✏️", ok: true,
                fb: "答對了!證據和 AI 不一樣時,由你來修正它。" },
              { label: "退回:看不清楚再照一次", icon: "🚫", fb: "X 光已經很清楚是玩具熊了,直接修正就可以。" },
            ]},
          { type: "mcq", art: "📦❓",
            scenario: "AI 標籤:「安全物品」。X 光影像:糊糊的一團,完全看不清楚。",
            q: "你的決定是?",
            opts: [
              { label: "接受:AI 說安全就安全", icon: "✅", fb: "看不清楚證據,就不能確定 AI 對不對喔。" },
              { label: "修正:隨便改一個標籤", icon: "✏️", fb: "沒有證據,我們也不知道該改成什麼。" },
              { label: "退回:請機器再檢查一次", icon: "🚫", ok: true,
                fb: "沒錯!證據不清楚時,先退回再檢查,或請大人幫忙確認。" },
            ]},
          { type: "mcq", art: "📦✏️📏",
            scenario: "AI 標籤:「文具箱」。X 光影像:鉛筆、尺和橡皮擦。",
            q: "你的決定是?",
            opts: [
              { label: "接受:證據和標籤相符", icon: "✅", ok: true, fb: "正確!檢查過證據再接受,才是好檢查員。" },
              { label: "修正:改成玩具箱", icon: "✏️", fb: "再看一次:是文具喔,AI 這次說對了。" },
              { label: "退回:總覺得怪怪的", icon: "🚫", fb: "證據清楚又相符,就可以放心接受囉。" },
            ]},
        ]},
        { t: "task", comp: "E3", kind: "quiz", title: "檢查員檢定:該接受、修正還是退回?", acts: [
          { type: "mcq", art: "📦🥕",
            scenario: "AI 標籤:「蔬菜箱」。X 光影像:一根根的紅蘿蔔。",
            q: "你的決定是?",
            opts: [
              { label: "接受", icon: "✅", ok: true, fb: "證據相符 → 接受。" },
              { label: "修正", icon: "✏️", fb: "證據和標籤是一致的喔。" },
              { label: "退回", icon: "🚫", fb: "證據已經很清楚了。" },
            ]},
          { type: "mcq", art: "📦⚽",
            scenario: "AI 標籤:「書本箱」。X 光影像:好幾顆足球。",
            q: "你的決定是?",
            opts: [
              { label: "接受", icon: "✅", fb: "證據跟標籤不一樣,不能接受喔。" },
              { label: "修正:改成運動用品箱", icon: "✏️", ok: true, fb: "證據清楚但 AI 錯了 → 由你修正。" },
              { label: "退回", icon: "🚫", fb: "證據夠清楚,可以直接修正。" },
            ]},
          { type: "mcq", art: "📦🌫️",
            scenario: "AI 標籤:「易碎品」。X 光影像:太暗了,幾乎全黑。",
            q: "你的決定是?",
            opts: [
              { label: "接受", icon: "✅", fb: "看不到證據就接受,太冒險了。" },
              { label: "修正", icon: "✏️", fb: "沒有證據,不知道要改成什麼。" },
              { label: "退回:再檢查一次", icon: "🚫", ok: true, fb: "證據不清 → 退回再查,必要時請大人幫忙。" },
            ]},
          { type: "mcq",
            q: "為什麼 AI 給的答案需要「查核」?",
            opts: [
              { label: "因為 AI 靠資料規律做判斷,遇到沒學過的情況就可能出錯", ok: true, fb: "完全正確!" },
              { label: "因為 AI 喜歡開玩笑騙人", fb: "AI 不會開玩笑,但它會出錯。" },
              { label: "不需要查核,AI 永遠是對的", fb: "AI 常常很準,但不是永遠對!" },
            ]},
          { type: "mcq",
            q: "AI 說話「非常有自信」的時候,代表它一定是對的嗎?",
            opts: [
              { label: "不一定,自信不等於正確,還是要看證據", ok: true, fb: "答對了,證據才是關鍵!" },
              { label: "對,越有自信就越正確", fb: "AI 錯的時候也可能講得很有自信喔。" },
              { label: "AI 有自信代表它心情好", fb: "AI 沒有心情啦!" },
            ]},
        ]},
        { t: "dialog", who: "npc",
          lines: [
            "今天的實習太成功了!整個港口都因為你變得更可靠。",
            "最後,阿浪要問你一個「大問題」——",
            "AI 幫了我們這麼多忙,為什麼我們還是不能把它說的話「全部直接相信」呢?",
          ],
          choices: [
            { label: "因為 AI 是靠資料規律運作的工具,會出錯,要自己查核證據",
              reply: "說得太好了!AI 是好幫手,但「看一看、想一想、再決定」的人,是你。這就是「問 AI」的智慧!" },
            { label: "因為 AI 想騙我們",
              reply: "AI 不會「想」騙人喔——它沒有想法。但它靠資料規律運作,資料沒教過的就可能出錯,所以要查核。記住:看一看、想一想、再決定!" },
            { label: "其實可以全部相信,只是老師叫我們不要",
              reply: "嗯……你今天親眼看到掃描機把玩具標成水果了吧?AI 真的會錯!所以才要看一看、想一想、再決定。這就是「問 AI」的智慧!" },
          ]},
      ],
    },

    /* ───────────────────────── 版本 C ─────────────────────────
       依 PO feedback:圖像化、低文字、高互動;
       E3 加重生成式 AI(LLM 文字 + 生圖找碴),新角色:生成式 AI 助理「小海」 */
    C: {
      desc: "圖像化任務(配對/拼句/快答)+ 生成式 AI 小海檢查台(蓋章/找碴)",
      steps: [
        { t: "dialog", who: "npc", lines: [
          "大家都說 AI 吊車「會思考」。真的嗎?",
          "今天我們打開它的腦袋看看!",
        ]},
        { t: "task", comp: "E2", kind: "learn", title: "打開 AI 的腦袋", acts: [
          { type: "imgpick",
            q: "吊車 AI 的「腦袋」裡,其實是哪一個?",
            opts: [
              { img: "brain-man.webp",   label: "小人在開車", fb: "裡面沒有小人喔!" },
              { img: "brain-data.webp",  label: "資料和規律", ok: true },
              { img: "brain-magic.webp", label: "魔法帽",     fb: "AI 不是魔法!" },
            ]},
          { type: "imgpick",
            q: "掃描機是怎麼「認出」蘋果的?",
            opts: [
              { img: "scan-read.webp",    label: "像人一樣看懂", fb: "它不是真的看懂喔" },
              { img: "scan-compare.webp", label: "跟學過的圖案比對", ok: true },
            ]},
          { type: "pairs",
            q: "把「怪怪的說法」和「真相」配成對!",
            pairs: [
              ["🧠 它會自己想", "📊 它在比對規律"],
              ["😢 它心情不好才答錯", "🕳️ 資料裡沒教過"],
              ["📖 它看得懂字", "🧩 它在對圖案"],
            ]},
          { type: "tokens",
            q: "拼出正確的一句話!",
            parts: ["AI 靠", "{資料}", "學到", "{規律}"],
            distractors: ["魔法", "心情"],
            hint: "想想腦袋圖裡看到什麼" },
          { type: "tokens",
            q: "再拼一句!",
            parts: ["資料裡", "{沒有}", "的東西,AI 容易", "{出錯}"],
            distractors: ["全部", "變聰明"] },
        ]},
        { t: "task", comp: "E2", kind: "quiz", title: "說法快篩", acts: [
          { type: "oxrush", q: "這個說法對嗎?",
            cards: [
              { icon: "📢", text: "「AI 廣播今天心情不好」", yes: false, fb: "AI 沒有心情" },
              { icon: "🗺️", text: "「導航是比對過去的資料」", yes: true },
              { icon: "🏗️", text: "「吊車 AI 什麼都懂」", yes: false, fb: "它只會資料教過的" },
              { icon: "🕳️", text: "「沒學過的,AI 容易錯」", yes: true },
            ]},
          { type: "imgpick",
            q: "AI 的「腦袋」其實是?",
            opts: [
              { img: "brain-data.webp", label: "資料和規律", ok: true },
              { img: "brain-man.webp",  label: "小人在開車", fb: "沒有小人!" },
            ]},
          { type: "tokens",
            q: "拼出 AI 的真面目!",
            parts: ["AI 是一種", "{工具}", ",它靠", "{資料}", "做事"],
            distractors: ["小人", "魔法"] },
        ]},
        { t: "dialog", who: "npc", lines: [
          "叮咚!港口來了新同事——生成式 AI 助理「小海」!",
          { who: "ai", text: "嗨!我是小海,我一秒寫廣播稿、一秒畫海報!" },
          "它超快,但它寫的、畫的都對嗎?",
          "你的三個印章:✅ 接受、✏️ 修正、🚫 退回。上工!",
        ]},
        { t: "task", comp: "E3", kind: "learn", title: "小海的作品檢查台", acts: [
          { type: "stamp",
            q: "比對兩邊,蓋下你的印章!",
            out: { label: "🤖 小海寫的廣播稿",
              text: "「海豚號 10:00 進港,請到 3 號碼頭迎接!」" },
            ev: { label: "📋 船班表",
              text: "海豚號\n進港 10:00\n3 號碼頭" },
            answer: "accept" },
          { type: "stamp",
            q: "這篇呢?",
            out: { label: "🤖 小海寫的廣播稿",
              text: "「海豚號 <mark>3:00</mark> 進港,請到 3 號碼頭迎接!」" },
            ev: { label: "📋 船班表",
              text: "海豚號\n進港 10:00\n3 號碼頭" },
            answer: "fix",
            hint: "時間一樣嗎?錯一點點就幫它修" },
          { type: "stamp",
            q: "旅客問:「港口有什麼好玩的?」小海答──",
            out: { label: "🤖 小海的回答",
              text: "「東碼頭有一座 500 年歷史的美人魚雕像,超級推薦!」" },
            ev: { label: "🗺️ 港口地圖", img: "port-map.webp" },
            answer: "reject",
            hint: "地圖上找得到雕像嗎?小海會「一本正經地編故事」!" },
          { type: "spot",
            q: "小海畫的協尋海報……哪裡怪怪的?點出來!",
            img: "dog-poster-5legs.webp",
            spots: [{ x: 63, y: 49, r: 14 }],
            hint: "數一數狗狗的腳🐾" },
          { type: "stamp",
            q: "找到問題了!那這張海報要?",
            out: { label: "🤖 小海畫的海報", img: "dog-poster-5legs.webp" },
            ev: { label: "📷 小狗本人的照片", img: "dog-photo.webp" },
            answer: "fix",
            hint: "圖是好的,只是腳多了一隻——請小海修!" },
          { type: "spot",
            q: "安全宣導圖也檢查一下:哪裡不合理?",
            img: "lifeguard-6fingers.webp",
            spots: [{ x: 36, y: 30, r: 17 }],
            hint: "船應該在哪裡呢?" },
          { type: "stamp",
            q: "最後一張:港口導覽圖!",
            out: { label: "🤖 小海畫的導覽圖", img: "port-map.webp" },
            ev: null,
            answer: "accept",
            hint: "有碼頭、燈塔、倉庫……畫得很好就大方接受!" },
        ]},
        { t: "task", comp: "E3", kind: "quiz", title: "一日檢查員檢定", acts: [
          { type: "stamp",
            q: "蓋章!",
            out: { label: "🤖 小海寫的廣播稿",
              text: "「貝殼號 14:00 出發,請旅客提早到 1 號碼頭。」" },
            ev: { label: "📋 船班表", text: "貝殼號\n出發 14:00\n1 號碼頭" },
            answer: "accept" },
          { type: "stamp",
            q: "蓋章!",
            out: { label: "🤖 小海寫的廣播稿",
              text: "「<mark>海馬號</mark> 16:00 進港!」" },
            ev: { label: "📋 船班表", text: "海豚號\n進港 16:00" },
            answer: "fix",
            hint: "船名對嗎?" },
          { type: "stamp",
            q: "旅客問燈塔,小海答──",
            out: { label: "🤖 小海的回答",
              text: "「我們的燈塔是全世界最高的,有 999 層樓!」" },
            ev: { label: "📖 燈塔資料", text: "港口燈塔\n樓層:3 層\n建於 60 年前" },
            answer: "reject",
            hint: "跟資料差太多了——整個退回!" },
          { type: "imgpick",
            q: "小海說話超有自信,所以?",
            opts: [
              { icon: "🔍", label: "還是要查證再決定", ok: true },
              { icon: "😍", label: "有自信就一定對", fb: "自信不等於正確!" },
            ]},
          { type: "oxrush", q: "檢查員觀念快答!",
            cards: [
              { icon: "🎨", text: "「AI 畫的圖可能有奇怪的錯,要檢查」", yes: true },
              { icon: "🤖", text: "「小海寫的一定都是真的」", yes: false, fb: "它可能一本正經地編故事" },
            ]},
        ]},
        { t: "dialog", who: "npc",
          lines: [
            "你今天蓋章蓋得又準又漂亮!",
            "最後一個問題──小海給的東西,我們該怎麼辦?",
          ],
          choices: [
            { label: "🍽️ 全部吞下去",
              reply: "等等!今天的美人魚雕像你忘了嗎?先查證──看一看、想一想、再決定!" },
            { label: "🔍 看一看、想一想,再決定",
              reply: "答對了!✅ 接受、✏️ 修正、🚫 退回──決定權永遠在你手上。這就是「問 AI」的智慧!" },
            { label: "🗑️ 全部丟掉",
              reply: "也不用啦!小海其實幫了很多忙。好的做法是:看一看、想一想、再決定!" },
          ]},
      ],
    },
    /* ───────────────────────── 版本 E ─────────────────────────
       《真相偵探社:港口大謎團》— 偵探推理遊戲
       E2 = 手電筒蒐證/證詞判別/證據板連線;E3 = 審問生成式 AI 嫌疑人
       測驗 = 謠言掃蕩 + 大結案之夜(Boss) */
    E: {
      desc: "🕵️ 遊戲《真相偵探社》:手電筒蒐證、證據板、審問室、大結案",
      steps: [
        { t: "dialog", who: "npc", lines: [
          "深夜警報!碼頭大亂,謠言滿天飛──",
          "「AI 吊車成精了!它會自己思考!」",
          "偵探社只相信證據。戴上手電筒,出發!🔦",
        ]},
        { t: "task", comp: "E2", kind: "learn", title: "蒐證行動:打開吊車的腦", acts: [
          { type: "spot", dark: true,
            q: "🔦 手電筒調查!找出吊車內部的 3 個真相證物",
            img: "crane-interior.webp",
            spots: [
              { x: 33, y: 60, r: 15 },
              { x: 50, y: 22, r: 11 },
              { x: 73, y: 58, r: 15 },
            ],
            hint: "移動手電筒,點亮三個發光的地方" },
          { type: "info", title: "🗂️ 證物入檔!",
            body: "📊 資料規律面板──它靠這個決定貨櫃放哪\n📷 鏡頭──它的「眼睛」只是感測器\n🔌 線路與馬達──照計算結果動作\n\n沒有大腦、沒有小人、沒有魔法。" },
          { type: "oxrush",
            q: "目擊者證詞一句一句來!可信的釘上證據板,謠言丟碎紙機!",
            btns: [
              { v: true,  icon: "📌", label: "釘上證據板" },
              { v: false, icon: "🗑️", label: "丟碎紙機" },
            ],
            cards: [
              { icon: "🌙", text: "「我看到吊車半夜在想事情!」", yes: false, fb: "它沒有腦,不會「想」!" },
              { icon: "📊", text: "「它是比對過去的資料規律來決定位置的」", yes: true },
              { icon: "😤", text: "「它昨天心情不好,才摔了貨櫃」", yes: false, fb: "AI 沒有心情!" },
              { icon: "🆕", text: "「沒學過的新貨櫃,它常常出錯」", yes: true },
            ]},
          { type: "pairs", style: "board",
            q: "證據板連線!把「現象」和「真正原因」釘成一對",
            pairs: [
              ["🏗️ 它把貨櫃放對位置", "📊 比對過去的資料規律"],
              ["❓ 它認錯新款貨櫃", "🕳️ 資料裡沒有這種例子"],
              ["📢 它「唸」出貨櫃編號", "🔉 照學過的發音規律轉成聲音"],
            ]},
          { type: "tokens",
            q: "寫下結案初稿!",
            parts: ["吊車沒有", "{思考}", ",它靠", "{資料}", "做事"],
            distractors: ["魔法", "心情"] },
        ]},
        { t: "task", comp: "E2", kind: "quiz", title: "偵探考核:謠言掃蕩", acts: [
          { type: "balloons",
            q: "謠言氣球飄上夜空!🎯 戳破謠言,放過真相!",
            items: [
              { text: "AI 吊車會自己思考", pop: true },
              { text: "AI 靠資料規律做事", pop: false, fb: "這句是真相,留著!" },
              { text: "AI 答錯是在鬧脾氣", pop: true },
              { text: "沒學過的,它容易錯", pop: false, fb: "真相!不能戳!" },
              { text: "機器裡住著小人", pop: true },
            ]},
          { type: "imgpick",
            q: "檔案照片:吊車的「腦」,是哪一張?",
            opts: [
              { img: "brain-data.webp", label: "資料和規律", ok: true },
              { img: "brain-man.webp",  label: "小人在開車", fb: "偵探調查過了:沒有小人!" },
            ]},
          { type: "tokens",
            q: "在偵探手冊寫下重點!",
            parts: ["AI 是", "{工具}", ",不是會思考的", "{小人}"],
            distractors: ["魔法師", "超人"] },
        ]},
        { t: "dialog", who: "npc", lines: [
          "新案件!嫌疑人:生成式 AI 助理「小海」。",
          { who: "ai", text: "我沒有說謊!我只是……很會接話嘛。" },
          "它的供詞真真假假。審問室見──你的三個章:採信🟢、修正✏️、駁回🚫!",
        ]},
        { t: "task", comp: "E3", kind: "learn", title: "審問室", acts: [
          { type: "stamp",
            q: "供詞 vs 證物,蓋下你的章!",
            stamps: [
              { id: "accept", icon: "🟢", label: "採信" },
              { id: "fix",    icon: "✏️", label: "修正" },
              { id: "reject", icon: "🚫", label: "駁回" },
            ],
            out: { label: "🤖 小海的供詞", text: "「海豚號 10:00 進港,停 3 號碼頭。」" },
            ev:  { label: "📋 船班表", text: "海豚號\n進港 10:00\n3 號碼頭" },
            answer: "accept" },
          { type: "stamp",
            q: "下一份供詞!",
            stamps: [
              { id: "accept", icon: "🟢", label: "採信" },
              { id: "fix",    icon: "✏️", label: "修正" },
              { id: "reject", icon: "🚫", label: "駁回" },
            ],
            out: { label: "🤖 小海的供詞", text: "「海豚號 <mark>3:00</mark> 進港,停 3 號碼頭。」" },
            ev:  { label: "📋 船班表", text: "海豚號\n進港 10:00\n3 號碼頭" },
            answer: "fix",
            hint: "只有一個數字錯──修正它!" },
          { type: "stamp",
            q: "小海越說越起勁……",
            stamps: [
              { id: "accept", icon: "🟢", label: "採信" },
              { id: "fix",    icon: "✏️", label: "修正" },
              { id: "reject", icon: "🚫", label: "駁回" },
            ],
            out: { label: "🤖 小海的供詞", text: "「案發當晚,東碼頭那座 500 年歷史的美人魚雕像,亮了一整夜!」" },
            ev:  { label: "🗺️ 港口地圖", img: "port-map.webp" },
            answer: "reject",
            hint: "地圖上有雕像嗎?它一本正經地編出了不存在的東西!" },
          { type: "spot",
            q: "🔍 證物鑑識:小海畫的協尋海報……圈出可疑之處!",
            img: "dog-poster-5legs.webp",
            spots: [{ x: 63, y: 49, r: 14 }],
            hint: "數一數狗狗的腳" },
          { type: "stamp",
            q: "鑑識完成,這張海報怎麼處理?",
            stamps: [
              { id: "accept", icon: "🟢", label: "採信" },
              { id: "fix",    icon: "✏️", label: "修正" },
              { id: "reject", icon: "🚫", label: "駁回" },
            ],
            out: { label: "🤖 小海畫的海報", img: "dog-poster-5legs.webp" },
            ev:  { label: "📷 小狗本人", img: "dog-photo.webp" },
            answer: "fix",
            hint: "圖是好的,只是腳多一隻──請它修!" },
        ]},
        { t: "task", comp: "E3", kind: "quiz", title: "大結案之夜(Boss)", acts: [
          { type: "stamp",
            q: "結案聽證會,連續判定開始!",
            stamps: [
              { id: "accept", icon: "🟢", label: "採信" },
              { id: "fix",    icon: "✏️", label: "修正" },
              { id: "reject", icon: "🚫", label: "駁回" },
            ],
            out: { label: "🤖 小海的供詞", text: "「貝殼號 14:00 出發,1 號碼頭。」" },
            ev:  { label: "📋 船班表", text: "貝殼號\n出發 14:00\n1 號碼頭" },
            answer: "accept" },
          { type: "stamp",
            q: "下一份!",
            stamps: [
              { id: "accept", icon: "🟢", label: "採信" },
              { id: "fix",    icon: "✏️", label: "修正" },
              { id: "reject", icon: "🚫", label: "駁回" },
            ],
            out: { label: "🤖 小海的供詞", text: "「<mark>海馬號</mark> 16:00 進港!」" },
            ev:  { label: "📋 船班表", text: "海豚號\n進港 16:00" },
            answer: "fix",
            hint: "船名對嗎?" },
          { type: "stamp",
            q: "最後一份供詞!",
            stamps: [
              { id: "accept", icon: "🟢", label: "採信" },
              { id: "fix",    icon: "✏️", label: "修正" },
              { id: "reject", icon: "🚫", label: "駁回" },
            ],
            out: { label: "🤖 小海的供詞", text: "「我們的燈塔全世界最高,有 999 層樓!」" },
            ev:  { label: "📖 燈塔資料", text: "港口燈塔\n樓層:3 層" },
            answer: "reject",
            hint: "差太多了──整份駁回!" },
          { type: "spot",
            q: "最後一件證物:安全宣導圖。圈出不合理之處!",
            img: "lifeguard-6fingers.webp",
            spots: [{ x: 36, y: 30, r: 17 }],
            hint: "船應該在哪裡?" },
          { type: "imgpick",
            q: "小海講得超有自信。偵探,你的態度是?",
            opts: [
              { icon: "🔍", label: "自信不等於正確,查證再蓋章", ok: true },
              { icon: "😍", label: "這麼有自信一定是真的", fb: "偵探只看證據!" },
            ]},
          { type: "info", title: "🏅 CASE CLOSED!",
            art: "🔍✅",
            body: "結案!吊車洗清了「成精」的冤屈,對你亮起感謝的大燈。\n小海也學會了:「下次我不確定的事,會先說我不確定。」\n\n你晉升──金牌偵探!" },
        ]},
        { t: "dialog", who: "npc",
          lines: [
            "偵探社的社訓,現在交給你──",
            "面對 AI 說的每一句話,金牌偵探會?",
          ],
          choices: [
            { label: "🍽️ 全部吞下去",
              reply: "偵探不吞供詞!記得美人魚雕像嗎?先查證據──看一看、想一想,再蓋章!" },
            { label: "🔍 查證據、想一想,再蓋章",
              reply: "正是社訓!採信🟢、修正✏️、駁回🚫──章,永遠在你手上。結案!🏅" },
            { label: "🗑️ 全部不信",
              reply: "小海也常說真話呀!全不信就浪費了好幫手。關鍵是:查了證據再決定!" },
          ]},
      ],
    },

    /* ───────────────────────── 版本 F ─────────────────────────
       🤖 機器人視覺化答題介面:出題者由機器人小海擔綱
       searching.json=小海思考中、mascot O/X 舉牌大卡、
       imgpick 大圖題、E3 蓋章台 out/ev 放圖 */
    F: {
      desc: "🤖 機器人視覺版:小海出題!lottie 思考動畫、O/X 舉牌二選一大卡、大圖選擇、蓋章檢查台",
      steps: [
        { t: "dialog", who: "npc", lines: [
          "今天的考官是機器人──生成式 AI 助理「小海」!",
          { who: "ai", text: "嗨!先猜猜:我的腦袋裡裝的是什麼?" },
          "跟著小海,打開 AI 的腦袋看看吧!",
        ]},
        { t: "task", comp: "E2", kind: "learn", title: "打開機器人的腦袋", acts: [
          { type: "imgpick",
            q: "小海的「腦袋」裡,其實是?",
            opts: [
              { img: "brain-man.webp",   label: "小人", fb: "裡面沒有小人!" },
              { img: "brain-data.webp",  label: "資料和規律", ok: true },
              { img: "brain-magic.webp", label: "魔法", fb: "AI 不是魔法!" },
            ]},
          { type: "mcq",
            lottie: "searching.json",
            q: "小海回答前,螢幕轉呀轉──它在做什麼?",
            opts: [
              { label: "比對學過的資料規律", icon: "📊", ok: true },
              { label: "慢慢想心事", icon: "💭", fb: "AI 沒有心事!" },
              { label: "打電話問朋友", icon: "📞", fb: "它不會這樣做喔。" },
            ]},
          { type: "imgpick",
            q: "掃描機怎麼「認出」蘋果?",
            opts: [
              { img: "scan-read.webp",    label: "像人一樣看懂", fb: "它不是真的看懂" },
              { img: "scan-compare.webp", label: "跟學過的圖案比對", ok: true },
            ]},
          { type: "sort2",
            q: "這些說法,小海該舉哪塊牌?",
            buckets: [
              { id: "fact", label: "說得對", svg: "mascot_hold_green_circle.svg" },
              { id: "myth", label: "怪怪的", svg: "mascot_hold_cross_circle.svg" },
            ],
            items: [
              { label: "吊車 AI 會自己思考", icon: "🏗️", bucket: "myth",
                fb: "它不會思考,是比對規律" },
              { label: "AI 從大量資料學到規律", icon: "📊", bucket: "fact" },
              { label: "AI 答錯是心情不好", icon: "🌧️", bucket: "myth",
                fb: "AI 沒有心情!" },
              { label: "沒學過的,AI 容易錯", icon: "🕳️", bucket: "fact" },
            ]},
          { type: "info", title: "小海的祕密",
            svg: "learnbot.svg",
            body: "📥 資料 → 📊 規律 → 📤 答案\n\nAI 是工具,不是會思考的小人。" },
        ]},
        { t: "task", comp: "E2", kind: "quiz", title: "機器人考官:快問快答", acts: [
          { type: "oxrush", q: "小海出題!這些說法對嗎?",
            cards: [
              { icon: "🏗️", text: "「吊車 AI 什麼都懂」", yes: false, fb: "它只會資料教過的" },
              { icon: "🗺️", text: "「導航是比對過去的資料」", yes: true },
              { icon: "📢", text: "「AI 廣播今天心情不好」", yes: false, fb: "AI 沒有心情" },
              { icon: "🆕", text: "「沒學過的,AI 容易錯」", yes: true },
            ]},
          { type: "imgpick",
            q: "AI 的腦袋,是哪一張?",
            opts: [
              { img: "brain-data.webp", label: "資料和規律", ok: true },
              { img: "brain-man.webp",  label: "小人在開車", fb: "沒有小人!" },
            ]},
          { type: "mcq",
            svg: "mascot_confusing.svg",
            q: "小海答錯了!最可能的原因是?",
            opts: [
              { label: "資料裡沒教過", icon: "🕳️", ok: true },
              { label: "它在鬧脾氣", icon: "😤", fb: "AI 不會鬧脾氣" },
              { label: "小人偷懶", icon: "🧍", fb: "沒有小人!" },
            ]},
          { type: "imgpick",
            q: "遇到沒看過的三角形貨櫃,小海會?",
            opts: [
              { svg: "mascot_confused.svg", label: "容易出錯", ok: true },
              { svg: "mascot_hold_green_circle.svg", label: "一定答對",
                fb: "資料沒教過,就容易錯!" },
            ]},
          { type: "sort2",
            q: "最後一輪!幫小海舉牌",
            buckets: [
              { id: "fact", label: "說得對", svg: "mascot_hold_green_circle.svg" },
              { id: "myth", label: "怪怪的", svg: "mascot_hold_cross_circle.svg" },
            ],
            items: [
              { label: "AI 是根據資料規律的工具", icon: "🔧", bucket: "fact" },
              { label: "掃描機讀得懂包裹的心事", icon: "📦", bucket: "myth",
                fb: "包裹沒有心事!" },
              { label: "AI 導航夢到了 B 航道", icon: "😴", bucket: "myth",
                fb: "AI 不會做夢!" },
              { label: "廣播 AI 照發音規律轉成聲音", icon: "🔉", bucket: "fact" },
            ]},
        ]},
        { t: "dialog", who: "npc", lines: [
          { who: "ai", text: "換我上工囉!一秒寫稿、一秒畫圖!" },
          "但它寫的、畫的,都對嗎?",
          "拿好三個印章:✅ 接受、✏️ 修正、🚫 退回!",
        ]},
        { t: "task", comp: "E3", kind: "learn", title: "小海作品檢查台", bot: "searching.json", acts: [
          { type: "stamp",
            q: "比對兩邊,蓋章!",
            out: { label: "🤖 小海寫的廣播稿",
              text: "「海豚號 10:00 進港,請到 3 號碼頭迎接!」" },
            ev: { label: "📋 船班表", text: "海豚號\n進港 10:00\n3 號碼頭" },
            answer: "accept" },
          { type: "stamp",
            q: "這篇呢?",
            out: { label: "🤖 小海寫的廣播稿",
              text: "「海豚號 <mark>3:00</mark> 進港,請到 3 號碼頭迎接!」" },
            ev: { label: "📋 船班表", text: "海豚號\n進港 10:00\n3 號碼頭" },
            answer: "fix",
            hint: "時間一樣嗎?錯一點點就幫它修" },
          { type: "stamp",
            q: "旅客問:「港口有什麼好玩的?」",
            out: { label: "🤖 小海的回答",
              text: "「東碼頭有 500 年歷史的美人魚雕像,超推薦!」" },
            ev: { label: "🗺️ 港口地圖", img: "port-map.webp" },
            answer: "reject",
            hint: "地圖上找得到雕像嗎?小海會一本正經地編故事!" },
          { type: "spot",
            q: "小海畫的協尋海報……哪裡怪怪的?點出來!",
            img: "dog-poster-5legs.webp",
            spots: [{ x: 63, y: 49, r: 14 }],
            hint: "數一數狗狗的腳🐾" },
          { type: "stamp",
            q: "找到了!這張海報要?",
            out: { label: "🤖 小海畫的海報", img: "dog-poster-5legs.webp" },
            ev: { label: "📷 小狗本人", img: "dog-photo.webp" },
            answer: "fix",
            hint: "圖是好的,只是腳多一隻──請小海修!" },
        ]},
        { t: "task", comp: "E3", kind: "quiz", title: "金牌檢查員檢定", bot: "painting.json", acts: [
          { type: "stamp",
            q: "蓋章!",
            out: { label: "🤖 小海寫的廣播稿",
              text: "「貝殼號 14:00 出發,請提早到 1 號碼頭。」" },
            ev: { label: "📋 船班表", text: "貝殼號\n出發 14:00\n1 號碼頭" },
            answer: "accept" },
          { type: "stamp",
            q: "蓋章!",
            out: { label: "🤖 小海寫的廣播稿",
              text: "「<mark>海馬號</mark> 16:00 進港!」" },
            ev: { label: "📋 船班表", text: "海豚號\n進港 16:00" },
            answer: "fix",
            hint: "船名對嗎?" },
          { type: "stamp",
            q: "旅客問燈塔,小海答──",
            out: { label: "🤖 小海的回答",
              text: "「我們的燈塔全世界最高,有 999 層樓!」" },
            ev: { label: "📖 燈塔資料", text: "港口燈塔\n樓層:3 層" },
            answer: "reject",
            hint: "差太多了──整份退回!" },
          { type: "spot",
            q: "安全宣導圖也檢查一下:哪裡不合理?",
            img: "lifeguard-6fingers.webp",
            spots: [{ x: 36, y: 30, r: 17 }],
            hint: "船應該在哪裡呢?" },
          { type: "imgpick",
            q: "小海講得超有自信,你會?",
            opts: [
              { svg: "mascot_mag.svg", label: "查證再決定", ok: true },
              { icon: "😍", label: "有自信就一定對", fb: "自信不等於正確!" },
            ]},
        ]},
        { t: "dialog", who: "npc",
          lines: [
            "檢定通過!小海對你舉起大大的 O!",
            "最後一題──小海給的東西,該怎麼辦?",
          ],
          choices: [
            { label: "🍽️ 全部吞下去",
              reply: "等等!美人魚雕像你忘了嗎?先查證──看一看、想一想、再決定!" },
            { label: "🔍 看一看、想一想,再決定",
              reply: "答對了!✅ 接受、✏️ 修正、🚫 退回──決定權永遠在你手上。這就是「問 AI」的智慧!" },
            { label: "🗑️ 全部丟掉",
              reply: "也不用啦!小海幫了很多忙。好的做法是:看一看、想一想、再決定!" },
          ]},
      ],
    },
  },
};
