/* ════════════════════════════════════════════════════════════
   管 AI・合作工廠(Manage AI)
   M1:依任務性質決定是否/選用哪個 AI 系統
       Basic:認識各種 AI 系統,以及它們各自擅長支援的任務。
   M2:比較不同 AI 的運作方式,為任務選擇合適的方法
       Basic:知道有些 AI 是「照規則做事」,
             有些 AI 是「從資料例子學規律」。
   ════════════════════════════════════════════════════════════ */

const MANAGE_MODULE = {
  id: "manage", domain: "manage", tag: "管AI", scene: "合作工廠", bg: "BK3.png",
  npc: { name: "奇奇廠長", img: "Maintenance workerhalf.png", standee: "Maintenance worker.png" },
  compMeta: {
    M1: { label: "管 AI 1", name: "認識 AI 幫手與它們擅長的任務" },
    M2: { label: "管 AI 2", name: "規則式 vs 學習式:選對方法" },
  },
  versions: {

    /* ───────────────────────── 版本 A ───────────────────────── */
    A: {
      desc: "任務派工板(工具配對)+ 兩條生產線(規則/學習分類機)",
      steps: [
        { t: "dialog", who: "npc", lines: [
          "哈囉!我是合作工廠的奇奇廠長,今天訂單多到爆炸,快來幫忙!",
          "我們工廠有一整排 AI 幫手:翻譯 AI、搜尋 AI、繪圖 AI、語音 AI……",
          "但是注意喔——每個 AI 幫手都有自己「擅長的任務」,派錯工,就會全場大亂!",
          "還有一個小祕密:有些任務其實「不需要 AI」,用普通工具就很好了。",
          "來,派工板亮起來了,由你來決定每個任務交給誰!",
        ]},
        { t: "task", comp: "M1", kind: "learn", title: "任務派工板", acts: [
          { type: "mcq", art: "📄➡️🌍",
            scenario: "任務 1:把玩具的說明書翻譯成英文,要給國外的客人。",
            q: "派給哪個幫手?",
            opts: [
              { label: "翻譯 AI:把一種語言轉成另一種語言", icon: "🌐", ok: true,
                fb: "答對!翻譯 AI 就是為語言轉換而生的。" },
              { label: "繪圖 AI:把文字變成圖片", icon: "🎨", fb: "繪圖 AI 只會畫圖,不會翻譯喔。" },
              { label: "計算機:算數字", icon: "🔢", fb: "計算機跟翻譯完全不搭啦!" },
            ]},
          { type: "mcq", art: "🧸🖼️",
            scenario: "任務 2:幫新玩具「跳跳兔」畫一張宣傳海報的草圖。",
            q: "派給哪個幫手?",
            opts: [
              { label: "繪圖 AI:依照描述生成圖片", icon: "🎨", ok: true,
                fb: "沒錯!畫面類的任務找繪圖 AI。" },
              { label: "翻譯 AI", icon: "🌐", fb: "翻譯 AI 不會畫畫喔。" },
              { label: "語音 AI:把文字唸出來", icon: "🔊", fb: "語音 AI 擅長聲音,不擅長畫圖。" },
            ]},
          { type: "mcq", art: "🔍📚",
            scenario: "任務 3:客人問「木頭玩具是用哪種木材做的最耐用?」需要查資料。",
            q: "派給哪個幫手?",
            opts: [
              { label: "搜尋引擎:幫你找到相關資料來源", icon: "🔍", ok: true,
                fb: "對!查資料先用搜尋工具,找到來源再自己判讀。" },
              { label: "繪圖 AI", icon: "🎨", fb: "畫圖沒辦法回答木材問題喔。" },
              { label: "碼表:計時", icon: "⏱️", fb: "碼表只會計時啦!" },
            ]},
          { type: "mcq", art: "⏰📅",
            scenario: "任務 4:提醒工人們「每天下午 3 點開品管會議」。",
            q: "派給哪個幫手?",
            opts: [
              { label: "行事曆鬧鐘就好:固定提醒不需要 AI", icon: "⏰", ok: true,
                fb: "聰明!固定時間提醒,普通工具就能做得又穩又好——不是每件事都需要 AI。" },
              { label: "找最貴的 AI 來提醒", icon: "💎", fb: "殺雞不用牛刀,固定提醒用鬧鐘就夠了!" },
              { label: "請翻譯 AI 提醒", icon: "🌐", fb: "翻譯 AI 的專長不是提醒喔。" },
            ]},
        ]},
        { t: "task", comp: "M1", kind: "quiz", title: "派工檢定:誰該上場?", acts: [
          { type: "mcq", q: "想「把中文故事唸成語音」放給小小孩聽,找哪個幫手?",
            opts: [
              { label: "語音 AI(文字轉語音)", ok: true, fb: "正確!" },
              { label: "搜尋引擎", fb: "搜尋引擎是找資料的。" },
              { label: "繪圖 AI", fb: "繪圖 AI 不會唸故事喔。" },
            ]},
          { type: "mcq", q: "想知道「今天新聞報了什麼玩具展消息」,第一步找?",
            opts: [
              { label: "搜尋引擎找新聞來源", ok: true, fb: "對,先找到資料來源!" },
              { label: "繪圖 AI 畫一則新聞", fb: "自己畫的可不是真新聞!" },
              { label: "鬧鐘", fb: "鬧鐘不會報新聞啦。" },
            ]},
          { type: "mcq", q: "外國客人來訪,想即時對話溝通,找哪個幫手?",
            opts: [
              { label: "翻譯 AI", ok: true, fb: "正確!" },
              { label: "計算機", fb: "數字幫不上對話喔。" },
              { label: "碼表", fb: "計時也幫不上!" },
            ]},
          { type: "mcq", q: "「每天固定量體溫並記在表格上」,最合適的做法是?",
            opts: [
              { label: "體溫計+表格就好,這種固定小事不需要 AI", ok: true,
                fb: "沒錯!先想「需不需要 AI」,是管理 AI 的第一步。" },
              { label: "一定要訓練一個量體溫 AI", fb: "不需要喔,普通工具就很可靠。" },
              { label: "請繪圖 AI 畫體溫", fb: "畫的體溫不是真的體溫啦!" },
            ]},
          { type: "mcq", q: "為什麼要「先認識每個 AI 擅長什麼」再派任務?",
            opts: [
              { label: "工具用在擅長的地方才幫得上忙,用錯地方反而幫倒忙", ok: true, fb: "管理者思維,滿分!" },
              { label: "因為 AI 會挑工作", fb: "AI 不會挑,是我們要挑對工具。" },
              { label: "不用認識,反正 AI 都一樣", fb: "不同 AI 差很多喔!" },
            ]},
        ]},
        { t: "dialog", who: "npc", lines: [
          "派工完美!工廠順利出貨啦!接下來帶你看工廠最深處的祕密——",
          "我們有兩條特別的生產線:「規則線」和「學習線」。",
          "「規則線」的機器照著人寫好的固定步驟做事,就像照食譜煮菜:條件一樣,動作就一樣。",
          "「學習線」的機器是看過大量例子後,自己抓出規律,就像看好多照片學會認東西。",
          "兩種都很有用,但要用對地方!來,你來判斷這些機器是哪一線的。",
        ]},
        { t: "task", comp: "M2", kind: "learn", title: "兩條生產線:規則?還是學習?", acts: [
          { type: "sort2",
            q: "這台機器是「照規則做事」,還是「從例子學規律」?",
            buckets: [
              { id: "rule", label: "規則線:照固定步驟", icon: "📏" },
              { id: "learn", label: "學習線:看例子學規律", icon: "🧠" },
            ],
            items: [
              { label: "輸送帶紅綠燈", desc: "設定好:每 30 秒切換一次號誌", icon: "🚦", bucket: "rule",
                fb: "固定時間、固定動作,是寫死的規則。" },
              { label: "瑕疵餅乾雷達", desc: "看過幾千張好/壞餅乾照片,學會挑出壞餅乾", icon: "🍪", bucket: "learn",
                fb: "「長怎樣算壞」很難用規則寫完,所以用大量例子學!" },
              { label: "自動門", desc: "感應器偵測到人就開門,沒人就關門", icon: "🚪", bucket: "rule",
                fb: "「有人→開;沒人→關」,一條簡單規則搞定。" },
              { label: "語音指令機", desc: "聽得懂工人各種口音說的「停機」", icon: "🎙️", bucket: "learn",
                fb: "每個人聲音都不同,要靠大量語音例子學規律。" },
              { label: "計算機", desc: "輸入 3+5,永遠輸出 8", icon: "🔢", bucket: "rule",
                fb: "數學規則固定,照規則算就對了。" },
              { label: "包裹照片分類機", desc: "看照片認出是玩具、文具還是食品", icon: "📦", bucket: "learn",
                fb: "認圖案要從大量照片例子學,規則寫不完!" },
            ]},
          { type: "mcq",
            scenario: "新任務:要挑出「形狀歪掉的餅乾」。工人試著寫規則:「缺一角算壞、太扁算壞、裂開算壞……」寫了三天還在寫,因為壞的樣子太多了!",
            q: "這個任務比較適合哪條線?",
            opts: [
              { label: "學習線:給機器看很多好與壞的例子,讓它自己抓規律", ok: true,
                fb: "正確!「樣子千變萬化、規則寫不完」的任務,就交給從例子學習的 AI。" },
              { label: "規則線:繼續寫規則,總有一天寫得完", fb: "壞餅乾的樣子無窮無盡,規則永遠寫不完啊!" },
              { label: "兩條線都不行,只能用人眼看", fb: "學習線最擅長這種任務喔!" },
            ]},
        ]},
        { t: "task", comp: "M2", kind: "quiz", title: "生產線檢定", acts: [
          { type: "sort2",
            q: "快速分類:規則?還是學習?",
            buckets: [
              { id: "rule", label: "照規則", icon: "📏" },
              { id: "learn", label: "從例子學", icon: "🧠" },
            ],
            items: [
              { label: "電梯", desc: "按 3 就到 3 樓", icon: "🛗", bucket: "rule", fb: "按鈕對應樓層,固定規則。" },
              { label: "相簿人臉搜尋", desc: "認出照片裡的家人", icon: "📷", bucket: "learn", fb: "認臉要靠大量例子學。" },
              { label: "定時灑水器", desc: "每天早上 7 點灑水 10 分鐘", icon: "💧", bucket: "rule", fb: "時間到就動作,規則式。" },
              { label: "垃圾郵件過濾", desc: "從大量郵件例子學會認出垃圾信", icon: "📧", bucket: "learn", fb: "垃圾信樣式一直變,要用學的。" },
            ]},
          { type: "mcq", q: "「規則式」機器的特色是?",
            opts: [
              { label: "條件一樣,動作永遠一樣,照人寫好的步驟執行", ok: true, fb: "正確!" },
              { label: "每天心情不同,做法不同", fb: "機器沒有心情,而且規則式最穩定。" },
              { label: "看例子自己學", fb: "那是學習式的特色喔。" },
            ]},
          { type: "mcq", q: "「學習式」AI 為什麼需要「大量例子」?",
            opts: [
              { label: "因為它要從例子中找出規律,例子越多元學得越好", ok: true, fb: "答對了!" },
              { label: "因為例子可以讓它吃飽", fb: "AI 不用吃飯啦!" },
              { label: "不需要例子,它天生就會", fb: "沒有例子它什麼都學不會喔。" },
            ]},
          { type: "mcq", q: "任務:「溫度超過 50 度就自動關機」。用哪種方法最合適?",
            opts: [
              { label: "規則式:一條清楚的規則就能做到,簡單又可靠", ok: true, fb: "對!規則清楚的任務用規則式,又穩又省。" },
              { label: "學習式:收集一萬筆關機例子來訓練", fb: "殺雞用牛刀啦!一條規則就搞定的事不必訓練 AI。" },
              { label: "都不行", fb: "規則式剛剛好!" },
            ]},
          { type: "mcq", q: "任務:「認出照片裡的 100 種商品」。用哪種方法最合適?",
            opts: [
              { label: "學習式:商品樣子太多變,用大量照片例子訓練", ok: true, fb: "正確!" },
              { label: "規則式:把每種商品的樣子寫成規則", fb: "100 種商品的各種角度光線……規則會寫到天荒地老!" },
              { label: "丟銅板決定", fb: "工廠可不能靠運氣!" },
            ]},
        ]},
        { t: "dialog", who: "npc",
          lines: [
            "今天你學會了廠長最重要的兩堂課:認識每個幫手的專長,還有分辨兩種 AI 的做事方法!",
            "下班前,奇奇要問你一個大問題——",
            "工具這麼多:普通工具、規則式機器、學習式 AI……到底「誰最強」?",
          ],
          choices: [
            { label: "沒有最強,只有最適合——看任務性質來選工具,決定權在人",
              reply: "太有廠長風範了!管 AI 的智慧就是:先看任務,再選工具;簡單的用規則,規則寫不完的用學習,不需要的就不用。你,就是最棒的管理者!" },
            { label: "學習式 AI 最強,所有事都該給它做",
              reply: "學習式很厲害,但「每 30 秒切換紅綠燈」給它做反而又貴又不穩!記住:沒有最強的工具,只有最適合任務的工具——由你來選,才是管理的智慧。" },
            { label: "普通工具最強,AI 都不可靠",
              reply: "普通工具很可靠,但「認出一百種商品」它可做不來!每種工具都有擅長的舞台:看任務、選工具,你就是做決定的那個人!" },
          ]},
      ],
    },

    /* ───────────────────────── 版本 B ───────────────────────── */
    B: {
      desc: "AI 幫手面試會(對話選才)+ 教機器認蘋果(規則爆炸實驗)",
      steps: [
        { t: "dialog", who: "npc", lines: [
          "號外號外!合作工廠今天舉辦「AI 幫手面試會」!",
          "一堆 AI 幫手來應徵,每個都說自己最厲害——但廠長我知道,重點是「任務需要什麼」。",
          "由你來當面試官!聽聽每位幫手的自我介紹,幫每個任務選出對的人選。",
          "偷偷提醒:有的任務啊,其實連 AI 都不需要……",
        ]},
        { t: "task", comp: "M1", kind: "learn", title: "AI 幫手面試會", acts: [
          { type: "chat", persona: "面試現場",
            turns: [
              { prompt: "任務一:「把產品目錄翻成日文」。應徵者:🌐 翻譯 AI:「我看過海量的中日文對照資料!」 🎨 繪圖 AI:「我可以把目錄畫得很漂亮!」——錄取誰?",
                opts: [
                  { label: "錄取翻譯 AI", ok: true,
                    reply: "🌐 翻譯 AI:「感謝錄取!馬上開工,產品目錄日文版一小時後交件!」",
                    fb: "任務是「語言轉換」,當然選翻譯 AI。看任務選人,面試官上手了!" },
                  { label: "錄取繪圖 AI",
                    reply: "🎨 繪圖 AI:「呃……我把目錄畫成了一幅畫,但客人還是看不懂日文……」",
                    fb: "畫得漂亮沒有用,任務要的是翻譯!要看任務需要什麼來選。" },
                ]},
              { prompt: "任務二:「幫吉祥物『齒輪熊』設計三款新造型草圖」。應徵者:🎨 繪圖 AI:「描述給我,我畫給你看!」 🔢 計算 AI:「我可以算出熊的體積!」——錄取誰?",
                opts: [
                  { label: "錄取繪圖 AI", ok: true,
                    reply: "🎨 繪圖 AI:「三款草圖完成:運動風、廚師風、太空風齒輪熊!」",
                    fb: "視覺設計的任務就是繪圖 AI 的主場!" },
                  { label: "錄取計算 AI",
                    reply: "🔢 計算 AI:「齒輪熊體積約 0.35 立方公尺……然後呢?」",
                    fb: "算體積對設計造型沒幫助啊!任務要的是「畫面」。" },
                ]},
              { prompt: "任務三:「每天下午 5 點提醒大家關燈下班」。應徵者:🤖 超級 AI:「我可以分析大家的行為模式再智慧提醒!」 ⏰ 老鬧鐘:「我……我只會準時響。」——錄取誰?",
                opts: [
                  { label: "錄取老鬧鐘", ok: true,
                    reply: "⏰ 老鬧鐘:「太感動了!我一定每天準時響,一秒都不差!」",
                    fb: "固定提醒不需要 AI!簡單任務用簡單工具,又穩又省——這就是管理智慧。" },
                  { label: "錄取超級 AI",
                    reply: "🤖 超級 AI:「分析中……根據大數據,建議您可能想在 5 點 03 分被提醒……」",
                    fb: "把簡單的事變複雜了!固定提醒交給鬧鐘就好,不是每件事都需要 AI。" },
                ]},
              { prompt: "任務四:「客人想知道倉庫裡還有幾箱積木」。應徵者:📋 庫存表:「打開我,數字都記在裡面。」 🎨 繪圖 AI:「我可以畫出很多箱積木的樣子!」——錄取誰?",
                opts: [
                  { label: "查庫存表", ok: true,
                    reply: "📋 庫存表:「積木庫存:42 箱。隨時歡迎查閱!」",
                    fb: "找「正確的紀錄」就去查紀錄,不是請 AI 生一個看起來像的答案!" },
                  { label: "請繪圖 AI 畫出來",
                    reply: "🎨 繪圖 AI:「我畫了 100 箱積木,壯觀吧!」…可是倉庫其實只有 42 箱。",
                    fb: "AI 生成的畫面不是事實!要查真正的紀錄。" },
                ]},
            ]},
        ]},
        { t: "task", comp: "M1", kind: "quiz", title: "面試官檢定", acts: [
          { type: "sort2",
            q: "這些任務,「適合請 AI 幫忙」還是「用普通工具就好」?",
            buckets: [
              { id: "ai", label: "適合 AI 幫忙", icon: "🤖" },
              { id: "simple", label: "普通工具就好", icon: "🧰" },
            ],
            items: [
              { label: "把一百封外文信翻成中文", icon: "✉️", bucket: "ai", fb: "大量語言轉換,翻譯 AI 的強項。" },
              { label: "每週三固定倒垃圾提醒", icon: "🗑️", bucket: "simple", fb: "固定提醒,鬧鐘就好。" },
              { label: "依描述生成新產品的示意圖", icon: "🖼️", bucket: "ai", fb: "生成圖像是繪圖 AI 的強項。" },
              { label: "量一塊木板的長度", icon: "📐", bucket: "simple", fb: "拿尺量最快最準!" },
            ]},
          { type: "mcq", q: "選 AI 幫手時,最該先問的問題是?",
            opts: [
              { label: "「這個任務需要什麼能力?」", ok: true, fb: "任務優先,工具其次——正確!" },
              { label: "「哪個 AI 名字最酷?」", fb: "名字酷不代表適合任務啦!" },
              { label: "「哪個 AI 最貴?」", fb: "貴不等於適合喔。" },
            ]},
          { type: "mcq", q: "「想聽昨天的會議紀錄內容」──最合適的幫手是?",
            opts: [
              { label: "語音 AI 把紀錄檔唸出來", ok: true, fb: "文字轉語音,正確!" },
              { label: "繪圖 AI 畫出會議的樣子", fb: "畫面不能代替紀錄內容喔。" },
              { label: "鬧鐘響一下", fb: "鬧鐘只會提醒時間啦。" },
            ]},
          { type: "mcq", q: "為什麼「查庫存數字」不該叫生成式 AI 直接回答?",
            opts: [
              { label: "因為正確數字在紀錄裡;AI 生成的內容可能看起來像真的但不是事實", ok: true,
                fb: "分清「查紀錄」和「生內容」,你已經是合格面試官!" },
              { label: "因為 AI 不喜歡數字", fb: "AI 沒有喜不喜歡,重點是資料正確性。" },
              { label: "其實應該叫 AI 回答比較快", fb: "快但可能錯!事實要查紀錄。" },
            ]},
          { type: "mcq", q: "哪一個是「好的派工決定」?",
            opts: [
              { label: "翻譯給翻譯 AI、畫圖給繪圖 AI、固定提醒給鬧鐘", ok: true, fb: "每個工具都在擅長的位置,完美!" },
              { label: "全部任務都給同一個最強 AI", fb: "沒有全能的工具喔。" },
              { label: "為了公平,用抽籤決定", fb: "派工看專長,不是看運氣!" },
            ]},
        ]},
        { t: "dialog", who: "npc", lines: [
          "面試會圓滿結束,每個幫手都在對的位置上!",
          "接著帶你去研發室——我們要教一台新機器「認出好蘋果」,把壞蘋果挑掉。",
          "工程師想了兩個方法。方法一:把「好蘋果的規則」全部寫給機器;方法二:給機器看大量好壞蘋果的「例子」讓它自己學。",
          "哪個方法好呢?我們兩個都做實驗看看!",
        ]},
        { t: "task", comp: "M2", kind: "learn", title: "研發室實驗:教機器認蘋果", acts: [
          { type: "info", title: "實驗一:用「規則」教",
            art: "🍎📏🤖",
            body: "工程師寫下規則:\n「紅色的是好蘋果。」→ 機器把綠蘋果全丟了!\n補規則:「綠色也可以。」→ 機器把還沒熟的也收了!\n再補:「有蟲洞不行、太軟不行、太小不行、擦傷……」\n\n規則越寫越多,第 47 條還在寫,例外永遠寫不完……實驗一:失敗😵" },
          { type: "mcq",
            q: "實驗一失敗的原因是什麼?",
            opts: [
              { label: "「好蘋果長怎樣」情況太多變,固定規則寫不完", ok: true,
                fb: "正確!樣子千變萬化的判斷任務,規則式會「規則爆炸」。" },
              { label: "工程師字寫得太醜,機器看不懂", fb: "跟字漂不漂亮沒關係啦!" },
              { label: "機器故意搗蛋", fb: "機器不會搗蛋,是方法不適合。" },
            ]},
          { type: "multi",
            q: "實驗二:改用「例子」教!要給機器一組好教材——選出 3 種最該放進教材的例子。",
            note: "選 3 種例子",
            need: 3,
            opts: [
              { id: "good_red", icon: "🍎", label: "各種好的紅蘋果照片", ok: true },
              { id: "good_green", icon: "🍏", label: "各種好的綠蘋果照片", ok: true },
              { id: "bad", icon: "🐛", label: "有蟲洞、碰傷的壞蘋果照片(標好「壞」)", ok: true },
              { id: "banana", icon: "🍌", label: "香蕉的照片" },
              { id: "cartoon", icon: "🖍️", label: "卡通蘋果貼紙" },
              { id: "one", icon: "1️⃣", label: "同一顆蘋果拍 100 張" },
            ],
            outcomes: [
              { when: "pass", pass: true, acc: 95, title: "實驗二:大成功!",
                msg: "紅的、綠的、好的、壞的例子都有,機器從多元例子中學到了「好蘋果的規律」——這就是學習式 AI!" },
              { has: ["banana"], pass: false, acc: 60, title: "咦?機器開始把香蕉當蘋果了",
                msg: "香蕉不是這個任務的例子喔!教材要跟任務有關。" },
              { has: ["cartoon"], pass: false, acc: 62, title: "機器分不清真蘋果和貼紙了",
                msg: "卡通貼紙跟真的蘋果長不一樣,會把機器教壞喔。" },
              { has: ["one"], pass: false, acc: 68, title: "機器只認得「那一顆」蘋果",
                msg: "同一顆拍再多張,機器也學不到「各種」蘋果的規律。例子要多元!" },
              { when: "default", pass: false, acc: 65, title: "再想想教材組合",
                msg: "好例子要「跟任務相關」而且「多元」:各種好蘋果+標記清楚的壞蘋果。" },
            ]},
          { type: "mcq",
            q: "兩個實驗做完了!「規則式」和「學習式」該怎麼選?",
            opts: [
              { label: "規則簡單明確的任務用規則式;樣子多變、規則寫不完的用學習式", ok: true,
                fb: "這就是為任務選對方法的智慧!" },
              { label: "永遠用學習式,規則式落伍了", fb: "「超過50度就關機」用規則式又穩又省喔!" },
              { label: "永遠用規則式,學習式太麻煩", fb: "認蘋果的實驗已經證明規則會寫不完啦!" },
            ]},
        ]},
        { t: "task", comp: "M2", kind: "quiz", title: "研發室檢定", acts: [
          { type: "mcq", q: "「照人寫好的固定步驟做事」的機器,我們叫它?",
            opts: [
              { label: "規則式", ok: true, fb: "正確!" },
              { label: "學習式", fb: "學習式是從例子學規律的喔。" },
              { label: "隨機式", fb: "工廠機器可不能隨機啦!" },
            ]},
          { type: "mcq", q: "「從大量例子中自己找出規律」的 AI,我們叫它?",
            opts: [
              { label: "學習式", ok: true, fb: "正確!" },
              { label: "規則式", fb: "規則式是照固定步驟的。" },
              { label: "許願式", fb: "沒有這種機器啦!" },
            ]},
          { type: "mcq", q: "任務:「按下綠色按鈕就啟動輸送帶」,選哪種方法?",
            opts: [
              { label: "規則式:一條規則清楚搞定", ok: true, fb: "簡單任務用簡單方法!" },
              { label: "學習式:收集一萬次按按鈕的例子", fb: "不需要喔,規則一條就夠。" },
              { label: "兩種都不行", fb: "規則式完全可以!" },
            ]},
          { type: "mcq", q: "任務:「聽懂全廠 200 位工人不同口音的語音指令」,選哪種方法?",
            opts: [
              { label: "學習式:用大量語音例子訓練", ok: true, fb: "口音千變萬化,用例子學,正確!" },
              { label: "規則式:把每個人的發音寫成規則", fb: "200 人的各種說法,規則會爆炸!" },
              { label: "請大家都不要說話", fb: "這樣工廠沒辦法運作啦!" },
            ]},
          { type: "mcq", q: "學習式 AI 的表現好不好,最大的關鍵是?",
            opts: [
              { label: "教材例子的品質:要相關、要多元、標記要正確", ok: true, fb: "抓到核心了!" },
              { label: "機器外殼的顏色", fb: "外觀不影響學習啦!" },
              { label: "放越多不相關的例子越好", fb: "不相關的例子反而會教壞它喔。" },
            ]},
        ]},
        { t: "dialog", who: "npc",
          lines: [
            "面試官+研發員一日體驗完成!工廠因為你運轉得又快又穩。",
            "最後一個大問題,想好再回答——",
            "工廠裡有普通工具、規則式機器、學習式 AI,身為管理者,你會怎麼決定「誰做哪件事」?",
          ],
          choices: [
            { label: "先看任務性質:簡單固定的用規則或普通工具,多變複雜的用學習式 AI",
              reply: "完美的管理者思維!任務永遠是老大,工具是為任務服務的。能這樣想,以後不管出現多新的 AI,你都知道怎麼管理它!" },
            { label: "全部交給最新最強的 AI 就對了",
              reply: "最新不一定最合適喔!記得老鬧鐘的故事嗎?簡單的事給簡單的工具,複雜多變的再請 AI——先看任務,再選工具,你說了算!" },
            { label: "我自己全部做,不用任何工具",
              reply: "你的責任感很棒!但一百封信自己翻會翻到睡著啊!好的管理者讓每個工具做擅長的事,自己做「決定」——這才是最重要的工作!" },
          ]},
      ],
    },
    /* ───────────────────────── 版本 C ─────────────────────────
       依 AILF Basic「In the Classroom」直翻成互動:
       M1 = 工具↔任務配對(工具販賣機)
       M2 = 垃圾分類機器人角色扮演:你「當」規則機器人,親身體驗
            規則的死板 → 再改用例子教學習機器人 */
    C: {
      desc: "AI 工具販賣機(投幣選工具)+ 你來當機器人!(親身體驗規則 vs 學習)",
      steps: [
        { t: "dialog", who: "npc", lines: [
          "訂單爆量!工廠的「AI 工具販賣機」開張了!",
          "投對幣,任務秒殺;投錯幣……會發生好笑的事。",
          "來,第一張任務卡出爐!",
        ]},
        { t: "task", comp: "M1", kind: "learn", title: "AI 工具販賣機", acts: [
          { type: "chat", persona: "🎰 工具販賣機",
            turns: [
              { prompt: "任務卡:「把 100 封外國訂單信翻成中文!」──投哪個幣?",
                opts: [
                  { label: "🌐 翻譯幣", ok: true,
                    reply: "叮!翻譯 AI 出動──100 封信,一小時翻好!",
                    fb: "任務要什麼能力,就投什麼幣!" },
                  { label: "🎨 繪圖幣", ok: false,
                    fb: "繪圖 AI 會把信畫成漫畫……客人看不懂啦!" },
                ]},
              { prompt: "任務卡:「幫新玩具『跳跳兔』畫宣傳圖!」──投哪個幣?",
                opts: [
                  { label: "🔢 計算幣", ok: false,
                    fb: "計算 AI:「跳跳兔有 37 個零件。」……然後呢?" },
                  { label: "🎨 繪圖幣", ok: true,
                    reply: "叮!繪圖 AI 畫出超可愛的跳跳兔海報!",
                    fb: "畫面類任務=繪圖 AI 的主場!" },
                ]},
              { prompt: "任務卡:「每天下午 3 點提醒大家開品管會議」──投哪個幣?",
                opts: [
                  { label: "🤖 超級 AI 幣(最貴的)", ok: false,
                    fb: "大砲打小鳥!固定提醒不需要 AI 喔。" },
                  { label: "⏰ 老鬧鐘幣(不用 AI)", ok: true,
                    reply: "叮!老鬧鐘:「這種小事包在我身上,一秒都不差!」",
                    fb: "簡單固定的事,用簡單工具最穩──不是每件事都需要 AI!" },
                ]},
              { prompt: "任務卡:「客人問:倉庫還剩幾箱積木?」──投哪個幣?",
                opts: [
                  { label: "📋 查庫存表(不用 AI)", ok: true,
                    reply: "叮!庫存表:「積木 42 箱。」正確數字,查表最快!",
                    fb: "要「事實數字」就去查紀錄,不是請 AI 猜!" },
                  { label: "🎨 繪圖幣", ok: false,
                    fb: "繪圖 AI 畫了 100 箱積木……可是倉庫只有 42 箱!" },
                ]},
            ]},
        ]},
        { t: "task", comp: "M1", kind: "quiz", title: "販賣機檢定:急單配對戰", acts: [
          { type: "pairs",
            q: "急單來了!把任務和對的工具配成對!",
            pairs: [
              ["✉️ 翻譯外國信件", "🌐 翻譯 AI"],
              ["🖼️ 畫產品海報", "🎨 繪圖 AI"],
              ["⏰ 固定時間提醒", "🔔 鬧鐘就好"],
              ["📊 查庫存數字", "📋 查紀錄表"],
            ]},
          { type: "oxrush", q: "廠長觀念快答!",
            cards: [
              { icon: "🧰", text: "「不是每件事都需要 AI」", yes: true },
              { icon: "💎", text: "「最貴的工具就是最好的」", yes: false, fb: "適合任務才是最好!" },
            ]},
        ]},
        { t: "dialog", who: "npc", lines: [
          "接下來是工廠最好玩的體驗課──",
          "回收區來了一台「規則寶」,它只會一個字一個字照規則做,完全不會想!",
          "想懂它?最快的方法:你、來、當、它!",
          "戴上機器人頭盔,規則只有一條:「圓圓的 → 回收桶」。開始!",
        ]},
        { t: "task", comp: "M2", kind: "learn", title: "你來當機器人!", acts: [
          { type: "info", title: "🤖 變身規則寶!",
            img: "robot-rule.webp",
            body: "你現在是規則寶。\n規則只有一條:「圓圓的 → 回收桶」。\n不准想、不准問,照規則做就對了!" },
          { type: "dragsort",
            q: "照規則做!圓圓的 → 回收桶,其他 → 垃圾桶",
            zones: [
              { id: "recycle", label: "回收桶", icon: "♻️" },
              { id: "trash",   label: "垃圾桶", icon: "🗑️" },
            ],
            items: [
              { icon: "🥫", label: "圓罐頭", zone: "recycle",
                fb: "圓的→回收桶,規則寶照做!" },
              { icon: "🍪", label: "圓餅乾", zone: "recycle",
                fb: "你是規則寶,不准想!圓的就進回收桶──連餅乾也是!" },
              { icon: "📦", label: "方紙箱", zone: "trash",
                fb: "紙箱明明可以回收……但規則沒寫「方的」,規則寶只好丟垃圾桶!" },
              { icon: "⚽", label: "足球", zone: "recycle",
                fb: "足球也進回收桶了!規則寶完全不會想哪裡怪怪的……" },
            ]},
          { type: "mcq",
            art: "🍪♻️⚽",
            q: "餅乾和足球都進了回收桶!問題出在哪?",
            opts: [
              { label: "規則太簡單,寫不完所有情況", ok: true },
              { label: "機器人壞掉了", fb: "它沒壞,它「完美地」照規則做了!" },
              { label: "餅乾自己跳進去的", fb: "是規則叫你丟的!" },
            ]},
          { type: "info", title: "🧠 學習寶登場!",
            img: "robot-learn.webp",
            body: "「規則寫不完?給我看例子,我自己學規律!」\n換個方法:用「標好的例子」教學習寶。" },
          { type: "multi",
            q: "幫學習寶挑 3 種教材!",
            note: "選 3 種",
            need: 3,
            opts: [
              { id: "rec",  icon: "♻️", label: "各種回收物的照片(標好「回收」)", ok: true },
              { id: "tra",  icon: "🗑️", label: "各種垃圾的照片(標好「垃圾」)", ok: true },
              { id: "food", icon: "🍪", label: "餅乾零食的照片(標好「不是回收」)", ok: true },
              { id: "one",  icon: "1️⃣", label: "同一個罐頭拍 100 張" },
              { id: "cat",  icon: "🐱", label: "貓咪的照片" },
            ],
            outcomes: [
              { when: "pass", pass: true, acc: 96, title: "學習寶學會了!",
                msg: "多元又標記清楚的例子,連餅乾都不會丟錯了!" },
              { has: ["one"], pass: false, acc: 62, title: "它只認得那一個罐頭…",
                msg: "同一張拍再多次,學不到「各種」東西的規律!" },
              { has: ["cat"], pass: false, acc: 58, title: "它開始把貓丟進回收桶?!",
                msg: "貓咪跟回收無關,不相關的教材會教壞它!" },
              { when: "default", pass: false, acc: 65, title: "教材再想想",
                msg: "教材要「跟任務相關」而且「多元、標記清楚」。" },
            ]},
          { type: "oxrush", q: "體驗完的心得快答!",
            cards: [
              { icon: "📏", text: "「規則清楚的小任務,規則寶最穩」", yes: true },
              { icon: "🌀", text: "「樣子千變萬化的任務,寫規則就夠了」", yes: false, fb: "規則會寫不完,要用例子學!" },
            ]},
        ]},
        { t: "task", comp: "M2", kind: "quiz", title: "指揮室檢定:誰上場?", acts: [
          { type: "dragsort",
            q: "新任務來了!該派規則寶還是學習寶?",
            zones: [
              { id: "rule",  label: "規則寶", icon: "📏" },
              { id: "learn", label: "學習寶", icon: "🧠" },
            ],
            items: [
              { icon: "🛗", label: "按 3 就到 3 樓的電梯", zone: "rule", fb: "規則一條,穩!" },
              { icon: "📦", label: "認出 100 種商品的照片", zone: "learn", fb: "樣子太多,用例子學!" },
              { icon: "🚦", label: "每 30 秒切換的紅綠燈", zone: "rule", fb: "固定規則就搞定!" },
              { icon: "🎙️", label: "聽懂全廠工人的各種口音", zone: "learn", fb: "口音千變萬化,用例子學!" },
            ]},
          { type: "tokens",
            q: "拼出廠長心法!",
            parts: ["規則寫得完用", "{規則寶}", ",樣子多變用", "{學習寶}"],
            distractors: ["最貴的", "用猜的"] },
          { type: "mcq",
            q: "學習寶表現好不好,最大關鍵是?",
            opts: [
              { label: "教材例子:相關、多元、標記正確", ok: true },
              { label: "機器人的顏色", fb: "顏色不影響學習啦!" },
              { label: "給它取一個帥氣的名字", fb: "名字帥不會變聰明!" },
            ]},
        ]},
        { t: "dialog", who: "npc",
          lines: [
            "今天你投過幣、當過機器人,還教會了學習寶!",
            "廠長的大問題──工具這麼多,誰決定「誰上場」?",
          ],
          choices: [
            { label: "🧑‍🏭 我!先看任務,再選最適合的工具",
              reply: "就是你!任務是老大,工具為任務服務──簡單的用規則,多變的用學習,不需要的就不用。你是最棒的管理者!" },
            { label: "🤖 讓 AI 自己決定就好",
              reply: "AI 不會替你想「該不該用它」喔!記得餅乾進回收桶的事──做決定的,永遠是人!" },
            { label: "🎲 抽籤決定",
              reply: "抽籤的話,可能會抽到繪圖 AI 去翻譯信……哈哈!看任務、選工具,你來決定才聰明!" },
          ]},
      ],
    },

    /* ───────────────────────── 版本 D ─────────────────────────
       M1 = 一週廠長行事曆(該不該用 AI 的節奏感決策)
       M2 = 機器人擂台賽(預測誰會贏 → 幫輸家補課) */
    D: {
      desc: "一週廠長行事曆(AI?不用 AI?)+ 機器人擂台賽(預測誰贏)",
      steps: [
        { t: "dialog", who: "npc", lines: [
          "恭喜升任「一日廠長」!",
          "這是你這週的行事曆──每天一個任務。",
          "廠長的第一課:先想「這件事需要 AI 嗎?」再決定派誰!",
        ]},
        { t: "task", comp: "M1", kind: "learn", title: "一週廠長行事曆", acts: [
          { type: "dragsort",
            q: "這件事,交給 AI?還是普通工具就好?",
            zones: [
              { id: "ai",     label: "交給 AI", icon: "🤖" },
              { id: "simple", label: "普通工具就好", icon: "🧰" },
            ],
            items: [
              { icon: "📅", label: "週一:把 100 封外國訂單信翻成中文", zone: "ai",
                fb: "大量翻譯=翻譯 AI 的強項!" },
              { icon: "📅", label: "週二:量一塊木板的長度", zone: "simple",
                fb: "拿尺量,3 秒搞定!" },
              { icon: "📅", label: "週三:幫新產品畫 3 張設計草圖", zone: "ai",
                fb: "生成圖像=繪圖 AI 上場!" },
              { icon: "📅", label: "週四:提醒大家 5 點關燈下班", zone: "simple",
                fb: "固定提醒,鬧鐘最穩!" },
              { icon: "📅", label: "週五:回答客人「倉庫剩幾箱」", zone: "simple",
                fb: "查庫存表!正確數字要查紀錄,不是請 AI 猜。" },
            ]},
          { type: "mcq",
            q: "廠長心法:決定用不用 AI,第一個要想的是?",
            opts: [
              { label: "這個任務需要什麼能力?", ok: true },
              { label: "哪台機器最新最帥?", fb: "帥不能翻譯信啦!" },
              { label: "今天星期幾?", fb: "跟星期幾沒關係!" },
            ]},
        ]},
        { t: "task", comp: "M1", kind: "quiz", title: "廠長檢定", acts: [
          { type: "pairs",
            q: "把任務和最合適的幫手配對!",
            pairs: [
              ["🗣️ 跟外國客人即時對話", "🌐 翻譯 AI"],
              ["📖 把說明書唸給大家聽", "🔊 語音 AI"],
              ["📏 量零件的尺寸", "🧰 用尺就好"],
            ]},
          { type: "oxrush", q: "快答!",
            cards: [
              { icon: "🧠", text: "「先看任務需要什麼,再選工具」", yes: true },
              { icon: "🤖", text: "「所有事都交給同一個 AI 最方便」", yes: false, fb: "沒有全能的工具!" },
              { icon: "📋", text: "「要正確數字就查紀錄,不是叫 AI 生一個」", yes: true },
            ]},
        ]},
        { t: "dialog", who: "npc", lines: [
          "叮叮叮──工廠擂台賽開打!",
          "紅方「規則寶」:照固定規則,又快又穩!",
          "藍方「學習寶」:看例子學規律,百變都不怕!",
          "每回合,你來預測誰會贏!",
        ]},
        { t: "task", comp: "M2", kind: "learn", title: "機器人擂台賽", acts: [
          { type: "info", title: "🥊 選手進場!",
            art: "📏 VS 🧠",
            body: "規則寶:「規則說一,我不做二!」\n學習寶:「給我例子,我自己學!」\n你是裁判兼預言家──猜猜每回合誰贏!" },
          { type: "mcq", art: "🔢",
            scenario: "第 1 回合:比算術「599 + 321」!",
            q: "誰會贏?",
            opts: [
              { label: "📏 規則寶", ok: true,
                fb: "" },
              { label: "🧠 學習寶", fb: "算術有固定規則,規則寶秒殺!學習寶還在翻例子……" },
            ]},
          { type: "mcq", art: "🍪",
            scenario: "第 2 回合:認出 100 種餅乾的包裝!",
            q: "誰會贏?",
            opts: [
              { label: "📏 規則寶", fb: "100 種包裝的規則寫到天亮也寫不完……學習寶看例子就會了!" },
              { label: "🧠 學習寶", ok: true },
            ]},
          { type: "mcq", art: "🔘",
            scenario: "第 3 回合:按綠色按鈕就啟動輸送帶!",
            q: "誰會贏?",
            opts: [
              { label: "📏 規則寶", ok: true },
              { label: "🧠 學習寶", fb: "一條規則就搞定的事,規則寶又快又省!" },
            ]},
          { type: "mcq", art: "🎙️",
            scenario: "第 4 回合:聽懂全廠 200 位工人的口音!",
            q: "誰會贏?",
            opts: [
              { label: "📏 規則寶", fb: "每個人口音都不同,規則爆炸!學習寶靠大量語音例子獲勝!" },
              { label: "🧠 學習寶", ok: true },
            ]},
          { type: "multi",
            q: "賽後特訓!學習寶輸了算術回合……咦,它需要特訓嗎?先幫「口音聽力」再進化:選 3 種好教材!",
            note: "選 3 種",
            need: 3,
            opts: [
              { id: "many", icon: "🗣️", label: "很多不同工人說「停機」的錄音", ok: true },
              { id: "fast", icon: "⚡", label: "有人說很快、有人說很慢的錄音", ok: true },
              { id: "noise", icon: "🏭", label: "吵雜工廠背景下的錄音", ok: true },
              { id: "one", icon: "1️⃣", label: "同一個人錄 100 次" },
              { id: "song", icon: "🎵", label: "流行歌曲" },
            ],
            outcomes: [
              { when: "pass", pass: true, acc: 97, title: "特訓成功!",
                msg: "多元的真實例子,學習寶聽誰說都懂了!" },
              { has: ["one"], pass: false, acc: 66, title: "它只聽得懂那一個人…",
                msg: "例子要多元,不是多次!" },
              { has: ["song"], pass: false, acc: 60, title: "它開始跟著唱歌了…",
                msg: "教材要跟任務相關啦!" },
              { when: "default", pass: false, acc: 68, title: "教材再挑挑",
                msg: "想想:什麼樣的錄音,最像它上場會聽到的?" },
            ]},
        ]},
        { t: "task", comp: "M2", kind: "quiz", title: "裁判檢定", acts: [
          { type: "mcq",
            q: "規則寶最大的優點是?",
            opts: [
              { label: "規則清楚的任務,做得又快又穩", ok: true },
              { label: "什麼都會", fb: "百變任務它就沒轍了!" },
              { label: "會自己學新東西", fb: "那是學習寶的能力!" },
            ]},
          { type: "mcq",
            q: "學習寶最大的優點是?",
            opts: [
              { label: "規則寫不完的多變任務,它從例子學得會", ok: true },
              { label: "永遠不會出錯", fb: "教材不好它也會錯喔!" },
              { label: "不需要任何資料", fb: "它最需要的就是例子!" },
            ]},
          { type: "dragsort",
            q: "加賽!誰上場?",
            zones: [
              { id: "rule",  label: "規則寶", icon: "📏" },
              { id: "learn", label: "學習寶", icon: "🧠" },
            ],
            items: [
              { icon: "🌡️", label: "超過 50 度就自動關機", zone: "rule", fb: "一條規則搞定!" },
              { icon: "📸", label: "認出照片裡的各種水果", zone: "learn", fb: "樣子多變,例子學!" },
              { icon: "💡", label: "有人經過就開燈", zone: "rule", fb: "感應+規則,穩!" },
            ]},
        ]},
        { t: "dialog", who: "npc",
          lines: [
            "擂台賽圓滿結束──其實沒有輸家,只有「用對地方」!",
            "大問題:如果兩隻機器人都想幫忙,你會怎麼安排?",
          ],
          choices: [
            { label: "⚖️ 看任務:規則清楚給規則寶,多變的給學習寶",
              reply: "完美裁判!沒有最強的機器人,只有最適合的安排──而做安排的人,就是你!" },
            { label: "🧠 全部給學習寶,它比較聰明",
              reply: "那按個按鈕它也要先看一萬個例子……規則寶會哭的!記住:看任務,選幫手!" },
            { label: "🙅 都不用,我自己來",
              reply: "100 封信自己翻會翻到明年!好廠長讓幫手做擅長的事,自己做最重要的「決定」!" },
          ]},
      ],
    },
    /* ───────────────────────── 版本 E ─────────────────────────
       《瘋狂訂單日:流水線指揮官》— 分流管理遊戲(Overcooked-lite)
       M1 = 輸送帶分流(任務球→工作站);M2 = 產線裝晶片 + 餵資料盒
       Boss = 超級訂單(流水線排序) */
    E: {
      desc: "🏭 遊戲《瘋狂訂單日》:輸送帶分流、產線裝晶片、規則爆炸、超級訂單",
      steps: [
        { t: "dialog", who: "npc", lines: [
          "叭叭叭──超級訂單日!工廠來了一批 AI 新幫手!",
          "派工之前,先認識他們──每一位的專長都不一樣。",
          "偷偷說:有些任務 AI 做不來,要交給「人類助手」喔!",
        ]},
        { t: "task", comp: "M1", kind: "learn", title: "AI 幫手圖鑑 & 分流大作戰", acts: [
          { type: "meet",
            q: "點擊每一位幫手,認識他們的專長!",
            items: [
              { id: "llm", name: "大型語言模型 AI", lottie: "idle.json",
                desc: "根據指令生成文字──寫介紹、擬草稿,交給我!" },
              { id: "vision", name: "影像辨識 AI", svg: "DogClassification.svg",
                desc: "能辨識影像中的事物──照片裡是什麼,我一眼認出!" },
              { id: "search", name: "搜尋引擎 AI", lottie: "searching.json",
                desc: "根據指令搜尋網路資料──最新消息我來找!" },
              { id: "gen", name: "生圖 AI", lottie: "painting.json",
                desc: "根據指令生成圖片──說出你想要的畫面!" },
            ]},
          { type: "conveyor",
            q: "任務球來了!派給對的幫手──有些要交給人類喔!",
            stations: [
              { id: "llm",    svg: "learnbot.svg",           label: "語言模型 AI" },
              { id: "vision", svg: "DogClassification.svg",  label: "影像辨識 AI" },
              { id: "search", lottie: "searching.json",      label: "搜尋引擎 AI" },
              { id: "gen",    svg: "ImageGen.svg",           label: "生圖 AI" },
              { id: "human",  icon: "🙋",                    label: "人類助手" },
            ],
            balls: [
              { icon: "📄", label: "把新玩具的特色,寫成一段介紹文字!", station: "llm",
                fb: "這是「生成文字」的任務──圖鑑裡誰的專長是文字?" },
              { icon: "📷", label: "這批倉庫照片裡裝的是什麼?認一認!", station: "vision",
                fb: "要「看懂照片」──影像的事找影像辨識 AI!" },
              { icon: "🔍", label: "查一查:今年的玩具安全新規定!", station: "search",
                fb: "要找「網路上的資料」──搜尋引擎 AI 出動!" },
              { icon: "😢", label: "新同事第一天上班好緊張,需要人陪他聊聊", station: "human",
                fb: "安慰人需要真心和同理心──AI 沒有真的感受,這件事交給人!" },
            ]},
        ]},
        { t: "task", comp: "M1", kind: "quiz", title: "派工檢定", acts: [
          { type: "conveyor",
            q: "檢定開始!四顆任務球,全部派對!",
            stations: [
              { id: "llm",    svg: "learnbot.svg",           label: "語言模型 AI" },
              { id: "vision", svg: "DogClassification.svg",  label: "影像辨識 AI" },
              { id: "search", lottie: "searching.json",      label: "搜尋引擎 AI" },
              { id: "gen",    svg: "ImageGen.svg",           label: "生圖 AI" },
              { id: "human",  icon: "🙋",                    label: "人類助手" },
            ],
            balls: [
              { icon: "🎨", label: "幫園遊會畫一張熱鬧的海報圖!", station: "gen",
                fb: "要「生成圖片」──說出畫面,誰畫得出來?" },
              { icon: "🧸", label: "這箱玩具的照片裡,哪些壞掉了?找出來!", station: "vision",
                fb: "從「照片」裡認出東西──影像辨識 AI 的主場!" },
              { icon: "⚖️", label: "兩位同事吵架了,怎麼處理才公平?", station: "human",
                fb: "公平要考慮感受與對錯──倫理判斷,交給人!" },
              { icon: "✍️", label: "幫忙起草一段活動邀請的文字!", station: "llm",
                fb: "起草「文字」──語言模型 AI 的專長!" },
            ]},
        ]},
        { t: "dialog", who: "npc", lines: [
          "分流漂亮!啊,差點忘了介紹──",
          "工廠還有一位「元老級」員工:規則機器人!",
          "他跟剛剛的 AI 同事不一樣:不靠大量資料學習,但你給他規則,他就一定遵守、絕不出錯──非常可靠!",
        ]},
        { t: "task", comp: "M2", kind: "learn", title: "規則機器人 vs AI 同事", acts: [
          { type: "meet",
            q: "先認識這位元老!",
            items: [
              { id: "rule", name: "規則機器人", svg: "ChatbotHelpYouLearn.svg",
                desc: "給我規則,我一定照做、絕不出錯!但沒寫進規則的事,我完全不會喔。" },
            ],
            hint: "點他一下,聽聽元老的自我介紹" },
          { type: "imgpick",
            q: "任務:「每天下午 5 點,自動關掉全廠的燈」──派誰?",
            opts: [
              { svg: "ChatbotHelpYouLearn.svg", label: "規則機器人", ok: true,
                fb: "" },
              { svg: "ImageGen.svg", label: "生圖 AI",
                fb: "畫圖幫不了關燈啦!固定時間+固定動作=清楚的規則,元老最可靠!" },
            ]},
          { type: "imgpick",
            q: "任務:「看照片認出輸送帶上的瑕疵零件」──派誰?",
            opts: [
              { svg: "ChatbotHelpYouLearn.svg", label: "規則機器人",
                fb: "壞零件的樣子千變萬化,規則寫不完!要看大量例子學的 AI 才行。" },
              { svg: "DogClassification.svg", label: "影像辨識 AI", ok: true },
            ]},
          { type: "imgpick",
            q: "任務:「溫度超過 50 度,立刻關機」──絕對不能出錯!派誰?",
            opts: [
              { lottie: "searching.json", label: "搜尋引擎 AI",
                fb: "這時候查資料就來不及啦!一條清楚規則+絕不出錯=規則機器人!" },
              { svg: "ChatbotHelpYouLearn.svg", label: "規則機器人", ok: true },
            ]},
          { type: "imgpick",
            q: "任務:「幫新產品寫一段介紹草稿」──派誰?",
            opts: [
              { svg: "learnbot.svg", label: "語言模型 AI", ok: true },
              { svg: "ChatbotHelpYouLearn.svg", label: "規則機器人",
                fb: "寫文章沒有固定規則可循──規則機器人只會照規則做事,生成文字要找語言模型 AI!" },
            ]},
        ]},
        { t: "task", comp: "M2", kind: "quiz", title: "元老 vs AI:派工檢定", acts: [
          { type: "imgpick",
            q: "「每週一早上 9 點,準時響鈴開工」──派誰?",
            opts: [
              { svg: "ChatbotHelpYouLearn.svg", label: "規則機器人", ok: true },
              { svg: "ImageGen.svg", label: "生圖 AI",
                fb: "固定時間的事,交給守規則的元老最穩!" },
            ]},
          { type: "imgpick",
            q: "「查網路上最新的機器保養方法」──派誰?",
            opts: [
              { svg: "ChatbotHelpYouLearn.svg", label: "規則機器人",
                fb: "「最新的資料」規則裡沒有──要上網搜尋的 AI!" },
              { lottie: "searching.json", label: "搜尋引擎 AI", ok: true },
            ]},
          { type: "imgpick",
            q: "「照著配方步驟,一步不差地調配清潔劑」──派誰?",
            opts: [
              { svg: "ChatbotHelpYouLearn.svg", label: "規則機器人", ok: true },
              { svg: "learnbot.svg", label: "語言模型 AI",
                fb: "照固定步驟、絕不出錯──這正是規則機器人的拿手絕活!" },
            ]},
          { type: "imgpick",
            q: "「幫慶功會畫一張海報」──派誰?",
            opts: [
              { svg: "ChatbotHelpYouLearn.svg", label: "規則機器人",
                fb: "畫畫沒有固定規則──生成圖片找生圖 AI!" },
              { svg: "ImageGen.svg", label: "生圖 AI", ok: true },
            ]},
        ]},
        { t: "dialog", who: "npc",
          lines: [
            "🎉 出貨量破紀錄!AI 同事和規則機器人都在對的位置上!",
            "廠長的大問題──什麼時候派規則機器人,什麼時候派 AI?",
          ],
          choices: [
            { label: "⚖️ 規則寫得清楚的交給規則機器人,多變要學的交給 AI",
              reply: "完美!規則清楚=元老最可靠;千變萬化=AI 從資料學。看任務、選幫手──你已經是真正的指揮官!" },
            { label: "🤖 全部交給 AI,比較新",
              reply: "新不一定適合!下午 5 點關燈這種事,元老一秒都不會差──可靠也是一種超能力!" },
            { label: "👴 全部交給元老,比較可靠",
              reply: "元老遇到「認照片」就投降啦──規則寫不完的事,要靠 AI 從例子學。兩種都用對地方,工廠才會轉!" },
          ]},
      ],
    },
    /* ───────────────────────── 版本 F ─────────────────────────
       🤖 機器人視覺化答題介面:
       M1 = 幫手選拔賽(機器人 SVG imgpick 大卡:字字寶/彩彩寶/找找寶/唸唸寶)
       M2 = 規則寶 vs 學習寶(robot-rule/robot-learn 全程視覺二選一大卡,
            searching.json 當「試跑中」待機動畫) */
    F: {
      desc: "🤖 機器人視覺版:幫手選拔大卡(imgpick)+ 規則寶 vs 學習寶視覺二選一",
      steps: [
        { t: "dialog", who: "npc", lines: [
          "歡迎來到合作工廠!我是奇奇廠長。",
          "工廠裡住著一群機器人幫手,每個都有絕活。",
          "任務來了——點出對的幫手,工廠就轉得動!",
        ]},
        { t: "task", comp: "M1", kind: "learn", title: "幫手選拔賽", acts: [
          { type: "info", title: "認識你的幫手團", svg: "teamupbot.svg",
            body: "幫手不是萬能,但各有絕活。\n派對工=工廠順;派錯工=大混亂!" },
          { type: "imgpick",
            q: "100 封外國信要翻成中文,誰上場?",
            opts: [
              { svg: "checkpromptbot.svg", label: "字字寶(翻譯)", ok: true },
              { svg: "mascot_painter.svg", label: "彩彩寶(畫圖)",
                fb: "彩彩寶會把信畫成漫畫,客人看不懂!" },
            ]},
          { type: "imgpick",
            q: "幫新玩具「跳跳兔」畫海報,誰上場?",
            opts: [
              { svg: "mascot_mag.svg", label: "找找寶(查資料)",
                fb: "找找寶只會找資料,不會畫畫喔!" },
              { svg: "mascot_painter.svg", label: "彩彩寶(畫圖)", ok: true },
              { svg: "checkpromptbot.svg", label: "字字寶(翻譯)",
                fb: "字字寶只懂文字,畫不出跳跳兔!" },
            ]},
          { type: "imgpick",
            q: "客人問:哪種木頭最耐用?要查資料!",
            opts: [
              { svg: "bookbot.svg", label: "唸唸寶(朗讀)",
                fb: "唸唸寶會唸,但不會找答案喔!" },
              { svg: "mascot_mag.svg", label: "找找寶(查資料)", ok: true },
              { svg: "mascot_painter.svg", label: "彩彩寶(畫圖)",
                fb: "畫出來的木頭,不會告訴你耐不耐用!" },
            ]},
          { type: "imgpick",
            q: "每天 3 點提醒開品管會,誰上場?",
            opts: [
              { svg: "mascot_use_computer.svg", label: "超級 AI",
                fb: "殺雞用牛刀!固定提醒,鬧鐘最穩。" },
              { icon: "⏰", label: "鬧鐘就好", ok: true },
            ]},
        ]},
        { t: "task", comp: "M1", kind: "quiz", title: "派工檢定", acts: [
          { type: "imgpick",
            q: "把故事唸給小小孩聽,誰上場?",
            opts: [
              { svg: "mascot_painter.svg", label: "彩彩寶(畫圖)",
                fb: "畫圖不會發出聲音喔!" },
              { svg: "bookbot.svg", label: "唸唸寶(朗讀)", ok: true },
              { svg: "mascot_mag.svg", label: "找找寶(查資料)",
                fb: "找資料不等於唸故事!" },
            ]},
          { type: "imgpick",
            q: "外國客人來訪,要即時對話!誰上場?",
            opts: [
              { svg: "checkpromptbot.svg", label: "字字寶(翻譯)", ok: true },
              { svg: "mascot_mag.svg", label: "找找寶(查資料)",
                fb: "現在要的是翻譯,查資料來不及啦!" },
            ]},
          { type: "imgpick",
            q: "量一塊木板的長度!",
            opts: [
              { icon: "📏", label: "用尺就好", ok: true },
              { svg: "mascot_mag.svg", label: "找找寶",
                fb: "拿尺量 3 秒搞定,不用麻煩 AI!" },
            ]},
          { type: "oxrush", q: "廠長快答!",
            cards: [
              { svg: "mascot_idle.svg", text: "先看任務,再選幫手", yes: true },
              { icon: "💎", text: "最貴的幫手就是最好的", yes: false,
                fb: "適合任務才是最好!" },
              { icon: "📋", text: "查庫存數字要查表,不是叫 AI 猜", yes: true },
            ]},
          { type: "mcq", svg: "mascot_thinking.svg",
            q: "為什麼要先認識幫手的絕活?",
            opts: [
              { label: "用對地方才幫得上忙", ok: true },
              { label: "因為幫手會挑工作", fb: "幫手不會挑,是你要選對!" },
              { label: "反正幫手都一樣", fb: "每個幫手差很多喔!" },
            ]},
        ]},
        { t: "dialog", who: "npc", lines: [
          "接下來,見見工廠最有名的雙胞胎機器人!",
          "哥哥「規則寶」照人寫好的步驟做,一步不差。",
          "弟弟「學習寶」看大量例子,自己學出規律。",
        ]},
        { t: "task", comp: "M2", kind: "learn", title: "雙胞胎試用日", bot: "searching.json", acts: [
          { type: "info", title: "📏 規則寶", img: "robot-rule.webp",
            body: "「規則說一,我不做二!」\n條件一樣,動作永遠一樣。" },
          { type: "info", title: "🧠 學習寶", img: "robot-learn.webp",
            body: "「給我看例子,我自己學!」\n例子越多元,學得越好。" },
          { type: "sort2",
            q: "這個任務,交給誰?",
            buckets: [
              { id: "rule",  label: "規則寶", img: "robot-rule.webp" },
              { id: "learn", label: "學習寶", img: "robot-learn.webp" },
            ],
            items: [
              { icon: "🚦", label: "輸送帶紅綠燈", desc: "每 30 秒切換一次", bucket: "rule",
                fb: "固定時間、固定動作,是規則寶的菜!" },
              { icon: "🍪", label: "挑出壞餅乾", desc: "壞的樣子千變萬化", bucket: "learn",
                fb: "「長怎樣算壞」寫不完,要看例子學!" },
              { icon: "🚪", label: "自動門", desc: "有人就開,沒人就關", bucket: "rule",
                fb: "一條規則就搞定,規則寶最穩!" },
              { icon: "🎙️", label: "聽懂各種口音的「停機」", desc: "每個人聲音都不同", bucket: "learn",
                fb: "口音千變萬化,要靠大量例子學!" },
            ]},
          { type: "mcq", svg: "mascot_confused.svg",
            scenario: "工人想用規則挑歪餅乾:「缺角算壞、太扁算壞……」寫到第 47 條還沒寫完!",
            q: "怎麼辦?",
            opts: [
              { label: "換學習寶:看好壞例子自己學", ok: true },
              { label: "繼續寫規則", fb: "壞餅乾的樣子永遠寫不完!" },
              { label: "不挑了直接出貨", fb: "客人會吃到壞餅乾啦!" },
            ]},
          { type: "multi",
            q: "餵學習寶!選 3 盒教材",
            note: "選 3 盒",
            need: 3,
            opts: [
              { id: "good",  icon: "🍪", label: "各種好餅乾(標「好」)", ok: true },
              { id: "bad",   icon: "🥴", label: "各種壞餅乾(標「壞」)", ok: true },
              { id: "light", icon: "💡", label: "不同光線拍的餅乾", ok: true },
              { id: "cat",   icon: "🐱", label: "工人的貓咪照片" },
              { id: "one",   icon: "1️⃣", label: "同一片餅乾拍 100 張" },
            ],
            outcomes: [
              { when: "pass", pass: true, acc: 97, title: "學習寶學會了!",
                msg: "好例、壞例、各種光線都有——連歪餅乾都逃不掉!" },
              { has: ["cat"], pass: false, acc: 55, title: "它把貓認成餅乾了!",
                msg: "不相關的教材會教壞它!" },
              { has: ["one"], pass: false, acc: 64, title: "它只認得那一片餅乾…",
                msg: "例子要多元,不是多次!" },
              { when: "default", pass: false, acc: 62, title: "教材再想想",
                msg: "上場會遇到什麼,教材就要有什麼。" },
            ]},
        ]},
        { t: "task", comp: "M2", kind: "quiz", title: "試跑檢定", bot: "searching.json", acts: [
          { type: "sort2",
            q: "試跑開始!這個任務交給誰?",
            buckets: [
              { id: "rule",  label: "規則寶", img: "robot-rule.webp" },
              { id: "learn", label: "學習寶", img: "robot-learn.webp" },
            ],
            items: [
              { icon: "🛗", label: "電梯", desc: "按 3 就到 3 樓", bucket: "rule",
                fb: "按鈕對應樓層,固定規則!" },
              { icon: "📷", label: "相簿認臉", desc: "認出照片裡的家人", bucket: "learn",
                fb: "認臉要靠大量例子學!" },
              { icon: "💧", label: "定時灑水器", desc: "每天 7 點灑 10 分鐘", bucket: "rule",
                fb: "時間到就動作,規則式!" },
              { icon: "📧", label: "垃圾信過濾", desc: "垃圾信樣式一直變", bucket: "learn",
                fb: "樣式一直變,要用學的!" },
            ]},
          { type: "imgpick",
            q: "「超過 50 度就自動關機」,誰上場?",
            opts: [
              { img: "robot-rule.webp", label: "規則寶", ok: true },
              { img: "robot-learn.webp", label: "學習寶",
                fb: "一條規則就搞定,不必收集一萬個例子!" },
            ]},
          { type: "imgpick",
            q: "「認出 100 種商品的照片」,誰上場?",
            opts: [
              { img: "robot-rule.webp", label: "規則寶",
                fb: "100 種商品的規則會寫到天荒地老!" },
              { img: "robot-learn.webp", label: "學習寶", ok: true },
            ]},
          { type: "mcq", svg: "mascot_thinking.svg",
            q: "學習寶為什麼需要大量例子?",
            opts: [
              { label: "例子多元才學得出規律", ok: true },
              { label: "因為它要吃飽", fb: "機器人不用吃飯啦!" },
              { label: "不用例子,天生就會", fb: "沒例子它什麼都學不會!" },
            ]},
          { type: "oxrush", q: "最後快答!",
            cards: [
              { img: "robot-rule.webp", text: "條件一樣,規則寶動作永遠一樣", yes: true },
              { img: "robot-learn.webp", text: "學習寶不用例子也能學會", yes: false,
                fb: "沒有例子,它什麼都學不會!" },
            ]},
        ]},
        { t: "dialog", who: "npc",
          lines: [
            "派工、選方法,你全都會了!",
            "下班前,廠長的大問題——",
            "幫手這麼多,到底「誰最強」?",
          ],
          choices: [
            { label: "沒有最強,只有最適合——由我看任務來選!",
              reply: "廠長認證!簡單的用規則,多變的用學習,不需要的就不用。這座工廠,交給你了!" },
            { label: "學習寶最強,全部給它做!",
              reply: "切個紅綠燈也要先看一萬個例子?又貴又慢!看任務、選幫手,你說了算。" },
            { label: "鬧鐘最強,又穩又便宜!",
              reply: "鬧鐘很穩,但它翻不了 100 封外國信!每個幫手都有舞台——做決定的人,是你。" },
          ]},
      ],
    },
  },
};
